In [95]:
import pandas as pd
import numpy as np
from IPython.display import display

base_path = 'C:/Users/언종/Desktop/data'

# 각 데이터 파일 불러오기
weather_forecast_1 = pd.read_csv(f'{base_path}/기상예측데이터_1.csv')
weather_forecast_2 = pd.read_csv(f'{base_path}/기상예측데이터_2.csv')
weather_actual_1 = pd.read_csv(f'{base_path}/기상실측데이터_1.csv')
weather_actual_2 = pd.read_csv(f'{base_path}/기상실측데이터_2.csv')
price_real_time = pd.read_csv(f'{base_path}/제주전력시장_시장전기가격_실시간가격.csv')
price_day_ahead = pd.read_csv(f'{base_path}/제주전력시장_시장전기가격_하루전가격.csv')
market_status = pd.read_csv(f'{base_path}/제주전력시장_현황데이터.csv')

In [96]:
def convert_columns(df):
    for col in df.columns:
        if col == 'location':
            continue  # location은 그대로 두기
        elif col == 'ts' or col == 'base_ts':
            df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')  # ts는 Int64형으로 변환
        else:
            df[col] = pd.to_numeric(df[col], errors='coerce').astype(float)  # 나머지는 float형으로 변환
    return df

In [97]:
# 각 데이터프레임에 변환 함수 적용
weather_forecast_1 = convert_columns(weather_forecast_1)
weather_forecast_2 = convert_columns(weather_forecast_2)
weather_actual_1 = convert_columns(weather_actual_1)
weather_actual_2 = convert_columns(weather_actual_2)
price_real_time = convert_columns(price_real_time)
price_day_ahead = convert_columns(price_day_ahead)
market_status = convert_columns(market_status)
for df_name, df in zip(['weather_forecast_1', 'weather_forecast_2', 'weather_actual_1', 'weather_actual_2', 
                        'price_real_time', 'price_day_ahead', 'market_status'], 
                       [weather_forecast_1, weather_forecast_2, weather_actual_1, weather_actual_2, 
                        price_real_time, price_day_ahead, market_status]):
    print(f"Object columns in {df_name}:")
    for col in df.select_dtypes(include='object').columns:
        unique_values = df[col].nunique()
        print(f"  {col} (unique values: {unique_values})")
    print("\n")
locations = pd.concat([
    weather_forecast_1[['location']],
    weather_forecast_2[['location']],
    weather_actual_1[['location']],
    weather_actual_2[['location']]
], axis=0)

Object columns in weather_forecast_1:
  location (unique values: 10)


Object columns in weather_forecast_2:
  location (unique values: 4)


Object columns in weather_actual_1:
  location (unique values: 10)


Object columns in weather_actual_2:
  location (unique values: 4)


Object columns in price_real_time:


Object columns in price_day_ahead:


Object columns in market_status:

In [98]:
# 모든 location 값을 모아 원핫 인코딩
locations_encoded = pd.get_dummies(locations)

# 원핫 인코딩 결과를 각 데이터프레임에 다시 병합
weather_forecast_1 = pd.concat([weather_forecast_1.drop(columns=['location']), locations_encoded[:len(weather_forecast_1)].reset_index(drop=True)], axis=1)
weather_forecast_2 = pd.concat([weather_forecast_2.drop(columns=['location']), locations_encoded[len(weather_forecast_1):len(weather_forecast_1) + len(weather_forecast_2)].reset_index(drop=True)], axis=1)
weather_actual_1 = pd.concat([weather_actual_1.drop(columns=['location']), locations_encoded[len(weather_forecast_1) + len(weather_forecast_2):len(weather_forecast_1) + len(weather_forecast_2) + len(weather_actual_1)].reset_index(drop=True)], axis=1)
weather_actual_2 = pd.concat([weather_actual_2.drop(columns=['location']), locations_encoded[len(weather_forecast_1) + len(weather_forecast_2) + len(weather_actual_1):].reset_index(drop=True)], axis=1)
datasets = {
    "weather_forecast_1": weather_forecast_1,
    "weather_forecast_2": weather_forecast_2,
    "weather_actual_1": weather_actual_1,
    "weather_actual_2": weather_actual_2,
    "price_real_time": price_real_time,
    "price_day_ahead": price_day_ahead,
    "market_status": market_status
}

In [99]:

# 'ts' 열을 1시간 단위로 그룹화하여 평균 리샘플링
weather_forecast_1['ts_hour'] = weather_forecast_1['ts'] // 3600 * 3600  # ts를 1시간 단위로 자름
weather_forecast_1 = weather_forecast_1.groupby('ts_hour').mean().reset_index()  # ts_hour를 기준으로 평균

# 동일한 방식으로 다른 데이터셋에도 적용
weather_forecast_2['ts_hour'] = weather_forecast_2['ts'] // 3600 * 3600
weather_forecast_2 = weather_forecast_2.groupby('ts_hour').mean().reset_index()

weather_actual_1['ts_hour'] = weather_actual_1['ts'] // 3600 * 3600
weather_actual_1 = weather_actual_1.groupby('ts_hour').mean().reset_index()

weather_actual_2['ts_hour'] = weather_actual_2['ts'] // 3600 * 3600
weather_actual_2 = weather_actual_2.groupby('ts_hour').mean().reset_index()

market_status['ts_hour'] = market_status['ts'] // 3600 * 3600
market_status = market_status.groupby('ts_hour').mean().reset_index()

# 'ts_hour'를 기준으로 병합
merged_data = price_real_time.copy()
merged_data['ts_hour'] = merged_data['ts'] // 3600 * 3600  # 1시간 단위로 자름

merged_data = pd.merge_asof(merged_data, weather_forecast_1, on='ts_hour', direction='nearest', suffixes=('', '_wf1'))
merged_data = pd.merge_asof(merged_data, weather_forecast_2, on='ts_hour', direction='nearest', suffixes=('', '_wf2'))
merged_data = pd.merge_asof(merged_data, weather_actual_1, on='ts_hour', direction='nearest', suffixes=('', '_wa1'))
merged_data = pd.merge_asof(merged_data, weather_actual_2, on='ts_hour', direction='nearest', suffixes=('', '_wa2'))
merged_data = pd.merge_asof(merged_data, market_status, on='ts_hour', direction='nearest', suffixes=('', '_ms'))

# 'ts_hour' 열을 최종 데이터프레임에서 삭제
merged_data.drop(columns=['ts_hour'], inplace=True)

# 결과 확인
print(merged_data.head())

weather_forecast_1 ts column null values: 8
weather_forecast_2 ts column null values: 2
weather_actual_1 ts column null values: 8
weather_actual_2 ts column null values: 2
price_real_time ts column null values: 0
price_day_ahead ts column null values: 0
market_status ts column null values: 0
           ts  실시간 임시 가격(원/kWh)  실시간 확정 가격(원/kWh)       base_ts        ts_wf1  \
0  1709218800             95.30             95.30  1709258400.0  1709305200.0
1  1709222400            107.39            107.39  1709258400.0  1709305200.0
2  1709226000             95.30             95.30  1709258400.0  1709305200.0
3  1709229600             87.89             87.89  1709258400.0  1709305200.0
4  1709233200             86.50             86.50  1709258400.0  1709305200.0

       temp  real_feel_temp  wet_bulb_temp  dew_point    wind_dir  ...  \
0  1.728394       -4.320987      -0.555556  -4.320987  335.555556  ...
1  1.728394       -4.320987      -0.555556  -4.320987  335.555556  ...
2  1.728394       -4.320987      -0.555556  -4.320987  335.555556  ...
3  1.728394       -4.320987      -0.555556  -4.320987  335.555556  ...
4  1.728394       -4.320987      -0.555556  -4.320987  335.555556  ...

   location_Yongsu-ri_wa2  location_location_wa2         ts_ms      공급능력(kW)  \
0                     0.0                    0.0  1709220450.0  1.359750e+06
1                     0.0                    0.0  1709224050.0  1.386333e+06
2                     0.0                    0.0  1709227650.0  1.378750e+06
3                     0.0                    0.0  1709231250.0  1.375167e+06
4                     0.0                    0.0  1709234850.0  1.382500e+06

       현재 수요(kW)  태양광 발전량kW)     풍력 발전량(kW)  신재생 발전량 총합(kW)     공급 예비력(kW)  \
0  785916.666667         0.0  206076.750000   221140.000000  573666.666667
1  749333.333333         0.0  232823.666667   247831.750000  637250.000000
2  731083.333333         0.0  223886.416667   239129.083333  647583.333333
3  739666.666667         0.0  220191.833333   235331.583333  635666.666667
4  748333.333333         0.0  226659.833333   241581.583333  634166.666667

      운영 예비력(kW)
0  250916.666667
1  313333.333333
2  323333.333333
3  310583.333333
4  307833.333333

[5 rows x 126 columns]

In [100]:
# 병합 결과 확인
print("Merged data shape:", merged_data.shape)
merged_data

Merged data shape: (5617, 126)

,ts,실시간 임시 가격(원/kWh),실시간 확정 가격(원/kWh),base_ts,ts_wf1,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_dir,...,location_Yongsu-ri_wa2,location_location_wa2,ts_ms,공급능력(kW),현재 수요(kW),태양광 발전량kW),풍력 발전량(kW),신재생 발전량 총합(kW),공급 예비력(kW),운영 예비력(kW)
0,1709218800,95.30,95.30,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709220450.0,1.359750e+06,785916.666667,0.0,206076.750000,221140.000000,573666.666667,250916.666667
1,1709222400,107.39,107.39,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709224050.0,1.386333e+06,749333.333333,0.0,232823.666667,247831.750000,637250.000000,313333.333333
2,1709226000,95.30,95.30,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709227650.0,1.378750e+06,731083.333333,0.0,223886.416667,239129.083333,647583.333333,323333.333333
3,1709229600,87.89,87.89,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709231250.0,1.375167e+06,739666.666667,0.0,220191.833333,235331.583333,635666.666667,310583.333333
4,1709233200,86.50,86.50,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709234850.0,1.382500e+06,748333.333333,0.0,226659.833333,241581.583333,634166.666667,307833.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5612,1729508400,156.43,155.32,1729389600.0,1729508400.0,22.901222,23.271600,21.790122,21.111133,44.222222,...,0.0,0.0,1729510050.0,1.065667e+06,737416.666667,0.0,101520.633333,109941.208333,323500.000000,311916.666667
5613,1729512000,156.35,155.32,1729389600.0,1729512000.0,23.271600,23.580244,22.037056,21.234589,46.777778,...,0.0,0.0,1729513650.0,1.051500e+06,703083.333333,0.0,87304.491667,95740.541667,343666.666667,267166.666667
5614,1729515600,155.89,154.80,1729389600.0,1729515600.0,22.962956,22.530867,21.975322,21.296311,47.111111,...,0.0,0.0,1729517250.0,1.038000e+06,677083.333333,0.0,77558.025000,85814.850000,356583.333333,280166.666667
5615,1729519200,155.23,154.89,1729389600.0,1729519200.0,23.086422,23.580256,22.037044,21.481478,47.444444,...,0.0,0.0,1729520550.0,1.029700e+06,650000.000000,0.0,66523.380000,74763.430000,375100.000000,282800.000000
5616,1729522800,155.32,155.32,1729432800.0,1729522800.0,22.530861,23.209872,21.851850,21.296311,48.111111,...,0.0,0.0,1729524450.0,1.003083e+06,601500.000000,0.0,37891.425000,46147.433333,396666.666667,266833.333333

In [101]:
merged_data.describe()

,ts,실시간 임시 가격(원/kWh),실시간 확정 가격(원/kWh),base_ts,ts_wf1,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_dir,...,location_Yongsu-ri_wa2,location_location_wa2,ts_ms,공급능력(kW),현재 수요(kW),태양광 발전량kW),풍력 발전량(kW),신재생 발전량 총합(kW),공급 예비력(kW),운영 예비력(kW)
count,5617.0,5617.000000,5617.000000,5617.0,5617.0,5617.000000,5617.000000,5617.000000,5617.000000,5617.000000,...,5617.0,5617.0,5617.0,5.617000e+03,5.617000e+03,5617.000000,5617.000000,5617.000000,5.617000e+03,5617.000000
mean,1719330922.485312,125.150995,125.330972,1719241307.032224,1719331114.758768,21.378487,22.727577,18.917616,17.165489,174.867367,...,0.0,0.0,1719332550.216208,1.301492e+06,7.460572e+05,63725.384679,56826.935887,132031.507540,5.537958e+05,355533.155540
std,5843432.136291,50.283059,49.772180,5842725.369611,5843101.209089,6.526103,9.215537,6.551300,7.342947,79.608606,...,0.0,0.0,5843440.54801,1.321587e+05,1.495677e+05,89376.849353,62573.850718,103349.951583,1.536809e+05,89513.924173
min,1709218800.0,-79.320000,-79.320000,1709258400.0,1709305200.0,1.604940,-5.308640,-0.555556,-4.320987,18.333333,...,0.0,0.0,1709220450.0,9.280833e+05,4.154167e+05,0.000000,0.000000,4319.064167,1.301667e+05,125166.666667
25%,1714273200.0,106.850000,106.850000,1714183200.0,1714273200.0,16.913589,16.172844,14.382700,12.407411,110.777778,...,0.0,0.0,1714274850.0,1.203667e+06,6.335833e+05,0.000000,7187.095667,41615.283333,4.485000e+05,295833.333333
50%,1719327600.0,139.270000,139.270000,1719237600.0,1719327600.0,22.098767,22.716033,19.753089,18.271600,165.888889,...,0.0,0.0,1719329250.0,1.298083e+06,7.218333e+05,9146.308333,31938.108333,107865.450000,5.565833e+05,345833.333333
75%,1724382000.0,154.800000,154.780000,1724292000.0,1724382000.0,26.975300,30.864200,24.938289,23.950600,228.888889,...,0.0,0.0,1724383650.0,1.392000e+06,8.371667e+05,109082.600000,88220.500000,205778.181818,6.540000e+05,404500.000000
max,1729522800.0,330.560000,314.820000,1729432800.0,1729522800.0,33.086422,41.666656,28.395056,27.222233,349.555556,...,0.0,0.0,1729524450.0,1.742750e+06,1.200429e+06,365975.833333,300261.833333,477293.500000,1.060500e+06,701166.666667

In [102]:
import numpy as np
start_timestamp = 1729612800  # 2024-10-23 00:00에 해당하는 Unix timestamp
timestamps = [start_timestamp + 3600 * i for i in range(24)]  # 1시간 간격으로 24개의 타임스탬프 생성

# 데이터프레임 생성
df_23day = pd.DataFrame({'ts': timestamps, 'smp_da': np.nan})  # 'smp_da'는 빈 값으로 초기화

# 결과 확인
print(df_23day)

            ts  smp_da
0   1729612800     NaN
1   1729616400     NaN
2   1729620000     NaN
3   1729623600     NaN
4   1729627200     NaN
5   1729630800     NaN
6   1729634400     NaN
7   1729638000     NaN
8   1729641600     NaN
9   1729645200     NaN
10  1729648800     NaN
11  1729652400     NaN
12  1729656000     NaN
13  1729659600     NaN
14  1729663200     NaN
15  1729666800     NaN
16  1729670400     NaN
17  1729674000     NaN
18  1729677600     NaN
19  1729681200     NaN
20  1729684800     NaN
21  1729688400     NaN
22  1729692000     NaN
23  1729695600     NaN

In [10]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
smp_rt_rc = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/smp-rt-rc/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()
print(smp_rt_rc)
smp_rt_rc_df = pd.DataFrame(smp_rt_rc)
smp_rt_rc_df

[{'ts': 1729612800, 'smp_rt': 100.23, 'smp_rc': 100.23}, {'ts': 1729616400, 'smp_rt': 92.35, 'smp_rc': 92.35}, {'ts': 1729620000, 'smp_rt': 92.27, 'smp_rc': 92.27}, {'ts': 1729623600, 'smp_rt': 0.0, 'smp_rc': 0.0}, {'ts': 1729627200, 'smp_rt': 0.0, 'smp_rc': 0.0}, {'ts': 1729630800, 'smp_rt': 100.25, 'smp_rc': 100.25}, {'ts': 1729634400, 'smp_rt': 100.25, 'smp_rc': 100.25}, {'ts': 1729638000, 'smp_rt': 0.0, 'smp_rc': 0.0}, {'ts': 1729641600, 'smp_rt': -48.0, 'smp_rc': -48.0}, {'ts': 1729645200, 'smp_rt': -78.74, 'smp_rc': -78.74}, {'ts': 1729648800, 'smp_rt': -78.74, 'smp_rc': -78.74}, {'ts': 1729652400, 'smp_rt': -78.74, 'smp_rc': -78.74}, {'ts': 1729656000, 'smp_rt': -78.74, 'smp_rc': -78.74}, {'ts': 1729659600, 'smp_rt': -78.74, 'smp_rc': -78.74}, {'ts': 1729663200, 'smp_rt': 216.99, 'smp_rc': 216.99}, {'ts': 1729666800, 'smp_rt': 134.74, 'smp_rc': 134.74}, {'ts': 1729670400, 'smp_rt': 134.74, 'smp_rc': 134.74}, {'ts': 1729674000, 'smp_rt': 139.6, 'smp_rc': 139.6}, {'ts': 1729677600, 'smp_rt': 139.33, 'smp_rc': 139.33}, {'ts': 1729681200, 'smp_rt': 134.75, 'smp_rc': 134.75}, {'ts': 1729684800, 'smp_rt': 153.19, 'smp_rc': 153.4}, {'ts': 1729688400, 'smp_rt': 106.56, 'smp_rc': 106.56}, {'ts': 1729692000, 'smp_rt': 104.94, 'smp_rc': 104.94}, {'ts': 1729695600, 'smp_rt': 105.29, 'smp_rc': 105.29}]

            ts  smp_rt  smp_rc
0   1729612800  100.23  100.23
1   1729616400   92.35   92.35
2   1729620000   92.27   92.27
3   1729623600    0.00    0.00
4   1729627200    0.00    0.00
5   1729630800  100.25  100.25
6   1729634400  100.25  100.25
7   1729638000    0.00    0.00
8   1729641600  -48.00  -48.00
9   1729645200  -78.74  -78.74
10  1729648800  -78.74  -78.74
11  1729652400  -78.74  -78.74
12  1729656000  -78.74  -78.74
13  1729659600  -78.74  -78.74
14  1729663200  216.99  216.99
15  1729666800  134.74  134.74
16  1729670400  134.74  134.74
17  1729674000  139.60  139.60
18  1729677600  139.33  139.33
19  1729681200  134.75  134.75
20  1729684800  153.19  153.40
21  1729688400  106.56  106.56
22  1729692000  104.94  104.94
23  1729695600  105.29  105.29

In [11]:
smp_rt_rc_df = smp_rt_rc_df.drop(columns=['smp_rt'])
smp_rt_rc_df = smp_rt_rc_df.rename(columns={'smp_rc': '실시간 확정 가격(원/kWh)'})
smp_rt_rc_df

            ts  실시간 확정 가격(원/kWh)
0   1729612800            100.23
1   1729616400             92.35
2   1729620000             92.27
3   1729623600              0.00
4   1729627200              0.00
5   1729630800            100.25
6   1729634400            100.25
7   1729638000              0.00
8   1729641600            -48.00
9   1729645200            -78.74
10  1729648800            -78.74
11  1729652400            -78.74
12  1729656000            -78.74
13  1729659600            -78.74
14  1729663200            216.99
15  1729666800            134.74
16  1729670400            134.74
17  1729674000            139.60
18  1729677600            139.33
19  1729681200            134.75
20  1729684800            153.40
21  1729688400            106.56
22  1729692000            104.94
23  1729695600            105.29

In [103]:
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# 실제 데이터와 예측 데이터에 대한 e_F를 계산하는 함수
def calculate_measure(actual, forecast):
    actual = np.array(actual)
    forecast = np.array(forecast)

    positive_index = actual > 0
    negative_index = actual <= 0

    # actual의 값이 0과 -1 사이에 있는 경우 -1로 처리
    actual[(actual <= 0) & (actual > -1)] = -1
    
    # 양수 및 음수 값의 개수
    n1 = np.sum(positive_index) + 1e-7
    n2 = np.sum(negative_index) + 1e-7

    # e1: 양수 가격 예측 오차율
    e1 = (
        np.sum(
            np.abs(actual[positive_index] - forecast[positive_index])
            / np.abs(actual[positive_index])
        )
        / n1
    )

    # e2: 음수 가격 예측 오차율
    e2 = (
        np.sum(
            np.abs(actual[negative_index] - forecast[negative_index])
            / np.abs(actual[negative_index])
        )
        / n2
    )

    TP = np.sum((forecast > 0) & (actual > 0))
    TN = np.sum((forecast <= 0) & (actual <= 0))
    FP = np.sum((forecast > 0) & (actual <= 0))
    FN = np.sum((forecast <= 0) & (actual > 0))

    # 정확도 계산
    Accuracy = (TP + TN) / (TP + TN + FP + FN)
    e_F = 0.2 * e1 + 0.8 * e2 - (Accuracy - 0.95)

    return e_F

# 데이터 준비
target_column = '실시간 확정 가격(원/kWh)'
X = merged_data.drop(columns=[target_column]).values
y = merged_data[target_column].values

# MinMaxScaler로 스케일링 적용
scaler_X, scaler_y = MinMaxScaler(), MinMaxScaler()
X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y.reshape(-1, 1))

# 시퀀스 데이터 생성
def create_sequences(X, y, sequence_length=5):
    X_seq, y_seq = [], []
    for i in range(sequence_length, len(X)):
        X_seq.append(X[i-sequence_length:i].flatten())
        y_seq.append(y[i])
    return np.array(X_seq), np.array(y_seq)

X_seq, y_seq = create_sequences(X_scaled, y_scaled, sequence_length=6)

# 훈련, 검증, 테스트 데이터 분할
X_train, X_temp, y_train, y_temp = train_test_split(X_seq, y_seq, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [104]:
xgb_model = xgb.XGBRegressor(objective='reg:squarederror')

# 모델 학습 및 검증 데이터에 대한 예측
xgb_model.fit(X_train, y_train)
y_val_pred = xgb_model.predict(X_val)

# 스케일링 복원 후 e_F 계산
y_val_pred_original = scaler_y.inverse_transform(y_val_pred.reshape(-1, 1)).flatten()
y_val_original = scaler_y.inverse_transform(y_val.reshape(-1, 1)).flatten()
e_F = calculate_measure(y_val_original, y_val_pred_original)
print("e_F value:", e_F)

e_F value: 18.350620135049688

In [105]:
last_sequence = X_seq[-1].reshape(1, -1)  # 마지막 시퀀스 데이터
predictions = []

for _ in range(24):
    prediction = xgb_model.predict(last_sequence)
    predictions.append(prediction[0])
    # 예측값을 시퀀스에 추가하여 다음 예측을 위해 시퀀스 업데이트
    last_sequence = np.concatenate([last_sequence[:, 1:], prediction.reshape(1, 1)], axis=1)

# 스케일링 복원
predictions = scaler_y.inverse_transform(np.array(predictions).reshape(-1, 1)).flatten()
print("Predictions for the next 24 hours:", predictions)


actual_24h = smp_rt_rc_df[target_column].values[-24:]
e_F = calculate_measure(actual_24h, predictions)
print("e_F for 24-hour prediction:", e_F)

Predictions for the next 24 hours: [153.32953   134.5349    119.1725     65.91573     0.2338865  54.36593
  96.213486    8.530571   35.269814   54.143536   -2.8658648  98.834885
 158.13667   116.598145   13.928313   -3.6027503  23.372963   78.272575
   6.936077   61.4237     84.10834    55.12004   129.29373    21.95017  ]
e_F for 24-hour prediction: 8.420918755467078

In [106]:
start_timestamp = 1729612800  # 2024-10-23 00:00에 해당하는 Unix timestamp
timestamps = [start_timestamp + 3600 * i for i in range(24)]

# 예측 결과를 DataFrame으로 저장
df_23day = pd.DataFrame({'ts': timestamps, 'smp_da': predictions})

In [107]:
df_23day

            ts      smp_da
0   1729612800  153.329529
1   1729616400  134.534897
2   1729620000  119.172501
3   1729623600   65.915733
4   1729627200    0.233886
5   1729630800   54.365929
6   1729634400   96.213486
7   1729638000    8.530571
8   1729641600   35.269814
9   1729645200   54.143536
10  1729648800   -2.865865
11  1729652400   98.834885
12  1729656000  158.136673
13  1729659600  116.598145
14  1729663200   13.928313
15  1729666800   -3.602750
16  1729670400   23.372963
17  1729674000   78.272575
18  1729677600    6.936077
19  1729681200   61.423698
20  1729684800   84.108337
21  1729688400   55.120041
22  1729692000  129.293732
23  1729695600   21.950171

In [108]:
actual = smp_rt_rc_df['실시간 확정 가격(원/kWh)'].values  # 실제 값
forecast = df_23day['smp_da'].values  # 예측 값

# 평가 함수 정의
def calculate_measure(actual, forecast):
    actual = np.array(actual)
    forecast = np.array(forecast)

    positive_index = actual > 0
    negative_index = actual <= 0

    # actual의 값이 0과 -1 사이에 있는 경우 -1로 처리
    actual[(actual <= 0) & (actual > -1)] = -1
    
    # 양수 및 음수 값의 개수
    n1 = np.sum(positive_index) + 1e-3  # 작은 값으로 설정
    n2 = np.sum(negative_index) + 1e-3

    # e1: 양수 가격 예측 오차율
    e1 = (
        np.sum(
            np.abs(actual[positive_index] - forecast[positive_index])
            / np.maximum(np.abs(actual[positive_index]), 1e-3)  # 작은 값으로 분모 안정화
        )
        / n1
    )

    # e2: 음수 가격 예측 오차율
    e2 = (
        np.sum(
            np.abs(actual[negative_index] - forecast[negative_index])
            / np.maximum(np.abs(actual[negative_index]), 1e-3)
        )
        / n2
    )

    TP = np.sum((forecast > 0) & (actual > 0))
    TN = np.sum((forecast <= 0) & (actual <= 0))
    FP = np.sum((forecast > 0) & (actual <= 0))
    FN = np.sum((forecast <= 0) & (actual > 0))

    # 정확도 계산
    Accuracy = (TP + TN) / (TP + TN + FP + FN)
    e_F = 0.2 * e1 + 0.8 * e2 - (Accuracy - 0.95)

    return e_F

# e_F 값 계산
e_F_value = calculate_measure(actual, forecast)
print("e_F value:", e_F_value)

e_F value: 8.420024408930118

In [ ]:
import json
import requests

result = {
    'submit_result': predictions.tolist() 
}

success = requests.post(
    'https://research-api.solarkim.com/submissions/cmpt-2024',
    data=json.dumps(result),
    headers={
        'Authorization': f'Bearer {"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"}'
    }
).json()

print(success)