In [20]:
import pandas as pd
import numpy as np
from IPython.display import display

base_path = 'C:/Users/언종/Desktop/data'

# 각 데이터 파일 불러오기
weather_forecast_1 = pd.read_csv(f'{base_path}/기상예측데이터_1.csv')
weather_forecast_2 = pd.read_csv(f'{base_path}/기상예측데이터_2.csv')
weather_actual_1 = pd.read_csv(f'{base_path}/기상실측데이터_1.csv')
weather_actual_2 = pd.read_csv(f'{base_path}/기상실측데이터_2.csv')
price_real_time = pd.read_csv(f'{base_path}/제주전력시장_시장전기가격_실시간가격.csv')
price_day_ahead = pd.read_csv(f'{base_path}/제주전력시장_시장전기가격_하루전가격.csv')
market_status = pd.read_csv(f'{base_path}/제주전력시장_현황데이터.csv')

In [21]:
price_day_ahead = price_day_ahead.rename(columns={'하루전가격(원/kWh)': 'smp_da'})

In [22]:
price_real_time = price_real_time.rename(columns={
    '실시간 임시 가격(원/kWh)': 'smp_rt',
    '실시간 확정 가격(원/kWh)': 'smp_rc'
})

In [23]:
market_status = market_status.rename(columns={
    '공급능력(kW)': 'supply_power',
    '현재 수요(kW)': 'present_load',
    '태양광 발전량kW)': 'power_solar',
    '풍력 발전량(kW)': 'power_wind',
    '신재생 발전량 총합(kW)': 'renewable_energy_total',
    '공급 예비력(kW)': 'supply_capacity',
    '운영 예비력(kW)': 'operation_capacity'
})

In [24]:
def convert_columns(df):
    for col in df.columns:
        if col == 'location':
            continue  
        elif col == 'ts' or col == 'base_ts':
            df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')  
        else:
            df[col] = pd.to_numeric(df[col], errors='coerce').astype(float)  
    return df

In [25]:
weather_forecast_1 = convert_columns(weather_forecast_1)
weather_forecast_2 = convert_columns(weather_forecast_2)
weather_actual_1 = convert_columns(weather_actual_1)
weather_actual_2 = convert_columns(weather_actual_2)
price_real_time = convert_columns(price_real_time)
price_day_ahead = convert_columns(price_day_ahead)
market_status = convert_columns(market_status)
for df_name, df in zip(['weather_forecast_1', 'weather_forecast_2', 'weather_actual_1', 'weather_actual_2', 
                        'price_real_time', 'price_day_ahead', 'market_status'], 
                       [weather_forecast_1, weather_forecast_2, weather_actual_1, weather_actual_2, 
                        price_real_time, price_day_ahead, market_status]):
    print(f"Object columns in {df_name}:")
    for col in df.select_dtypes(include='object').columns:
        unique_values = df[col].nunique()
        print(f"  {col} (unique values: {unique_values})")
    print("\n")
locations = pd.concat([
    weather_forecast_1[['location']],
    weather_forecast_2[['location']],
    weather_actual_1[['location']],
    weather_actual_2[['location']]
], axis=0)

Object columns in weather_forecast_1:
  location (unique values: 10)


Object columns in weather_forecast_2:
  location (unique values: 4)


Object columns in weather_actual_1:
  location (unique values: 10)


Object columns in weather_actual_2:
  location (unique values: 4)


Object columns in price_real_time:


Object columns in price_day_ahead:


Object columns in market_status:

In [26]:
# 모든 location 값을 모아 원핫 인코딩
locations_encoded = pd.get_dummies(locations)

# 원핫 인코딩 결과를 각 데이터프레임에 다시 병합
weather_forecast_1 = pd.concat([weather_forecast_1.drop(columns=['location']), locations_encoded[:len(weather_forecast_1)].reset_index(drop=True)], axis=1)
weather_forecast_2 = pd.concat([weather_forecast_2.drop(columns=['location']), locations_encoded[len(weather_forecast_1):len(weather_forecast_1) + len(weather_forecast_2)].reset_index(drop=True)], axis=1)
weather_actual_1 = pd.concat([weather_actual_1.drop(columns=['location']), locations_encoded[len(weather_forecast_1) + len(weather_forecast_2):len(weather_forecast_1) + len(weather_forecast_2) + len(weather_actual_1)].reset_index(drop=True)], axis=1)
weather_actual_2 = pd.concat([weather_actual_2.drop(columns=['location']), locations_encoded[len(weather_forecast_1) + len(weather_forecast_2) + len(weather_actual_1):].reset_index(drop=True)], axis=1)

In [27]:
# 'ts' 열을 1시간 단위로 그룹화하여 평균 리샘플링
weather_forecast_1['ts_hour'] = weather_forecast_1['ts'] // 3600 * 3600  # ts를 1시간 단위로 자름
weather_forecast_1 = weather_forecast_1.groupby('ts_hour').mean().reset_index()  # ts_hour를 기준으로 평균

# 동일한 방식으로 다른 데이터셋에도 적용
weather_forecast_2['ts_hour'] = weather_forecast_2['ts'] // 3600 * 3600
weather_forecast_2 = weather_forecast_2.groupby('ts_hour').mean().reset_index()

weather_actual_1['ts_hour'] = weather_actual_1['ts'] // 3600 * 3600
weather_actual_1 = weather_actual_1.groupby('ts_hour').mean().reset_index()

weather_actual_2['ts_hour'] = weather_actual_2['ts'] // 3600 * 3600
weather_actual_2 = weather_actual_2.groupby('ts_hour').mean().reset_index()

market_status['ts_hour'] = market_status['ts'] // 3600 * 3600
market_status = market_status.groupby('ts_hour').mean().reset_index()

# 'ts_hour'를 기준으로 병합
merged_data = price_real_time.copy()
merged_data['ts_hour'] = merged_data['ts'] // 3600 * 3600  # 1시간 단위로 자름

merged_data = pd.merge_asof(merged_data, weather_forecast_1, on='ts_hour', direction='nearest', suffixes=('', '_wf1'))
merged_data = pd.merge_asof(merged_data, weather_forecast_2, on='ts_hour', direction='nearest', suffixes=('', '_wf2'))
merged_data = pd.merge_asof(merged_data, weather_actual_1, on='ts_hour', direction='nearest', suffixes=('', '_wa1'))
merged_data = pd.merge_asof(merged_data, weather_actual_2, on='ts_hour', direction='nearest', suffixes=('', '_wa2'))
merged_data = pd.merge_asof(merged_data, market_status, on='ts_hour', direction='nearest')

# 'ts_hour' 열을 최종 데이터프레임에서 삭제
merged_data.drop(columns=['ts_hour'], inplace=True)

# 결과 확인
merged_data

,ts_x,smp_rt,smp_rc,base_ts,ts_wf1,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_dir,...,location_Yongsu-ri_wa2,location_location_wa2,ts_y,supply_power,present_load,power_solar,power_wind,renewable_energy_total,supply_capacity,operation_capacity
0,1709218800,95.30,95.30,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709220450.0,1.359750e+06,785916.666667,0.0,206076.750000,221140.000000,573666.666667,250916.666667
1,1709222400,107.39,107.39,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709224050.0,1.386333e+06,749333.333333,0.0,232823.666667,247831.750000,637250.000000,313333.333333
2,1709226000,95.30,95.30,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709227650.0,1.378750e+06,731083.333333,0.0,223886.416667,239129.083333,647583.333333,323333.333333
3,1709229600,87.89,87.89,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709231250.0,1.375167e+06,739666.666667,0.0,220191.833333,235331.583333,635666.666667,310583.333333
4,1709233200,86.50,86.50,1709258400.0,1709305200.0,1.728394,-4.320987,-0.555556,-4.320987,335.555556,...,0.0,0.0,1709234850.0,1.382500e+06,748333.333333,0.0,226659.833333,241581.583333,634166.666667,307833.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5612,1729508400,156.43,155.32,1729389600.0,1729508400.0,22.901222,23.271600,21.790122,21.111133,44.222222,...,0.0,0.0,1729510050.0,1.065667e+06,737416.666667,0.0,101520.633333,109941.208333,323500.000000,311916.666667
5613,1729512000,156.35,155.32,1729389600.0,1729512000.0,23.271600,23.580244,22.037056,21.234589,46.777778,...,0.0,0.0,1729513650.0,1.051500e+06,703083.333333,0.0,87304.491667,95740.541667,343666.666667,267166.666667
5614,1729515600,155.89,154.80,1729389600.0,1729515600.0,22.962956,22.530867,21.975322,21.296311,47.111111,...,0.0,0.0,1729517250.0,1.038000e+06,677083.333333,0.0,77558.025000,85814.850000,356583.333333,280166.666667
5615,1729519200,155.23,154.89,1729389600.0,1729519200.0,23.086422,23.580256,22.037044,21.481478,47.444444,...,0.0,0.0,1729520550.0,1.029700e+06,650000.000000,0.0,66523.380000,74763.430000,375100.000000,282800.000000
5616,1729522800,155.32,155.32,1729432800.0,1729522800.0,22.530861,23.209872,21.851850,21.296311,48.111111,...,0.0,0.0,1729524450.0,1.003083e+06,601500.000000,0.0,37891.425000,46147.433333,396666.666667,266833.333333

In [18]:
merged_data.describe()

,ts,smp_rt,smp_rc,base_ts,ts_wf1,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_dir,...,location_Yongsu-ri_wa2,location_location_wa2,ts_ms,supply_power,present_load,power_solar,power_wind,renewable_energy_total,supply_capacity,operation_capacity
count,5617.0,5617.000000,5617.000000,5617.0,5617.0,5617.000000,5617.000000,5617.000000,5617.000000,5617.000000,...,5617.0,5617.0,5617.0,5.617000e+03,5.617000e+03,5617.000000,5617.000000,5617.000000,5.617000e+03,5617.000000
mean,1719330922.485312,125.150995,125.330972,1719241307.032224,1719331114.758768,21.378487,22.727577,18.917616,17.165489,174.867367,...,0.0,0.0,1719332550.216208,1.301492e+06,7.460572e+05,63725.384679,56826.935887,132031.507540,5.537958e+05,355533.155540
std,5843432.136291,50.283059,49.772180,5842725.369611,5843101.209089,6.526103,9.215537,6.551300,7.342947,79.608606,...,0.0,0.0,5843440.54801,1.321587e+05,1.495677e+05,89376.849353,62573.850718,103349.951583,1.536809e+05,89513.924173
min,1709218800.0,-79.320000,-79.320000,1709258400.0,1709305200.0,1.604940,-5.308640,-0.555556,-4.320987,18.333333,...,0.0,0.0,1709220450.0,9.280833e+05,4.154167e+05,0.000000,0.000000,4319.064167,1.301667e+05,125166.666667
25%,1714273200.0,106.850000,106.850000,1714183200.0,1714273200.0,16.913589,16.172844,14.382700,12.407411,110.777778,...,0.0,0.0,1714274850.0,1.203667e+06,6.335833e+05,0.000000,7187.095667,41615.283333,4.485000e+05,295833.333333
50%,1719327600.0,139.270000,139.270000,1719237600.0,1719327600.0,22.098767,22.716033,19.753089,18.271600,165.888889,...,0.0,0.0,1719329250.0,1.298083e+06,7.218333e+05,9146.308333,31938.108333,107865.450000,5.565833e+05,345833.333333
75%,1724382000.0,154.800000,154.780000,1724292000.0,1724382000.0,26.975300,30.864200,24.938289,23.950600,228.888889,...,0.0,0.0,1724383650.0,1.392000e+06,8.371667e+05,109082.600000,88220.500000,205778.181818,6.540000e+05,404500.000000
max,1729522800.0,330.560000,314.820000,1729432800.0,1729522800.0,33.086422,41.666656,28.395056,27.222233,349.555556,...,0.0,0.0,1729524450.0,1.742750e+06,1.200429e+06,365975.833333,300261.833333,477293.500000,1.060500e+06,701166.666667

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

# 한글 폰트 설정
plt.rcParams['font.family'] = 'Malgun Gothic'  # Windows의 경우 'Malgun Gothic' 사용
plt.rcParams['axes.unicode_minus'] = False  # 음수 기호가 깨지는 현상 방지

# 상관계수 행렬 계산
correlation_matrix = merged_data.corr()

# 절대 상관계수 0.5 이상인 변수만 선택
high_corr = correlation_matrix[(correlation_matrix >= 0.3) | (correlation_matrix <= -0.5)]

# 히트맵 크기 설정 및 시각화
plt.figure(figsize=(30, 30))
sns.heatmap(high_corr, annot=True, cmap='coolwarm', fmt=".2f", cbar=True, linewidths=0.5, linecolor='gray')
plt.title("상관계수가 높은 변수들 간의 상관관계")
plt.show()

In [ ]:
import numpy as np
start_timestamp = 1729612800  # 2024-10-23 00:00에 해당하는 Unix timestamp
timestamps = [start_timestamp + 3600 * i for i in range(24)]  # 1시간 간격으로 24개의 타임스탬프 생성

# 데이터프레임 생성
df_23day = pd.DataFrame({'ts': timestamps, 'smp_da': np.nan})  # 'smp_da'는 빈 값으로 초기화

# 결과 확인
print(df_23day)

In [ ]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
smp_rt_rc = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/smp-rt-rc/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()
print(smp_rt_rc)
smp_rt_rc_df = pd.DataFrame(smp_rt_rc)
smp_rt_rc_df

In [ ]:
smp_rt_rc_df = smp_rt_rc_df.drop(columns=['smp_rt'])
smp_rt_rc_df = smp_rt_rc_df.rename(columns={'smp_rc': '실시간 확정 가격(원/kWh)'})
smp_rt_rc_df

In [ ]:
import numpy as np
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error

# 데이터 준비
target_column = '실시간 확정 가격(원/kWh)'
X = merged_data.drop(columns=[target_column]).values
y = merged_data[target_column].values

# MinMaxScaler로 스케일링 적용
scaler_X, scaler_y = MinMaxScaler(), MinMaxScaler()
X_scaled = scaler_X.fit_transform(X)
y_scaled = scaler_y.fit_transform(y.reshape(-1, 1))

# 상관계수 계산 및 상관계수가 절대값 0.3 이상인 변수 찾기
correlation_matrix = merged_data.corr()
high_corr_features = correlation_matrix[target_column][(correlation_matrix[target_column].abs() >= 0.3)].index.tolist()

# 실제 X_scaled의 범위 내에 있는 인덱스만 포함
high_corr_indices = [
    merged_data.columns.get_loc(col)
    for col in high_corr_features
    if col in merged_data.columns and col != target_column
]

# 상관계수가 높은 변수들에 가중치 적용 (10배)
X_weighted = X_scaled.copy()
for idx in high_corr_indices:
    if idx < X_scaled.shape[1]:  # 인덱스가 유효한지 확인
        X_weighted[:, idx] *= 3 # 상관계수가 높은 변수들에 가중치 10 적용

# 시퀀스 데이터 생성
def create_sequences(X, y, sequence_length=6):
    X_seq, y_seq = [], []
    for i in range(sequence_length, len(X)):
        X_seq.append(X[i-sequence_length:i].flatten())
        y_seq.append(y[i])
    return np.array(X_seq), np.array(y_seq)

X_seq, y_seq = create_sequences(X_weighted, y_scaled, sequence_length=6)

# 훈련, 검증, 테스트 데이터 분할
X_train, X_temp, y_train, y_temp = train_test_split(X_seq, y_seq, test_size=0.2, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# XGBoost 모델 정의 및 학습
model = XGBRegressor(objective='reg:squarederror', eval_metric='mae', n_estimators=100)
model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=True)

# 테스트 데이터 예측
y_pred = model.predict(X_test)

# 결과를 스케일링 복원
y_pred_rescaled = scaler_y.inverse_transform(y_pred.reshape(-1, 1))
y_test_rescaled = scaler_y.inverse_transform(y_test)

# MAE 계산
mae = mean_absolute_error(y_test_rescaled, y_pred_rescaled)
print("테스트 데이터 MAE:", mae)

In [ ]:
correlation_matrix = merged_data.corr()

# target_column과 상관관계가 절대값 0.5 이상인 변수들 찾기
threshold = 0.0  # 임계값 설정
high_corr_features = correlation_matrix[target_column][(correlation_matrix[target_column].abs() >= threshold)].index.tolist()

# 상관관계가 높은 변수 출력
print("가중치를 더 크게 줄 변수들:")
for feature in high_corr_features:
    corr_value = correlation_matrix[target_column][feature]
    print(f"{feature}: 상관계수 = {corr_value:.2f}")

In [ ]:
xgb_model = XGBRegressor(objective='reg:squarederror')
xgb_model.fit(X_train, y_train)
y_val_pred = xgb_model.predict(X_val)

In [ ]:
last_sequence = X_seq[-1].reshape(1, -1)  # 마지막 시퀀스 데이터
predictions = []

for _ in range(24):
    prediction = xgb_model.predict(last_sequence)
    predictions.append(prediction[0])
    # 예측값을 시퀀스에 추가하여 다음 예측을 위해 시퀀스 업데이트
    last_sequence = np.concatenate([last_sequence[:, 1:], prediction.reshape(1, 1)], axis=1)

# 스케일링 복원
predictions = scaler_y.inverse_transform(np.array(predictions).reshape(-1, 1)).flatten()
print("Predictions for the next 24 hours:", predictions)

In [ ]:
start_timestamp = 1729612800  # 2024-10-23 00:00에 해당하는 Unix timestamp
timestamps = [start_timestamp + 3600 * i for i in range(24)]

# 예측 결과를 DataFrame으로 저장
df_23day = pd.DataFrame({'ts': timestamps, 'smp_da': predictions})

In [ ]:
df_23day

In [ ]:
actual = smp_rt_rc_df['실시간 확정 가격(원/kWh)'].values  # 실제 값
forecast = df_23day['smp_da'].values  # 예측 값

# 평가 함수 정의
def calculate_measure(actual, forecast):
    actual = np.array(actual)
    forecast = np.array(forecast)

    positive_index = actual > 0
    negative_index = actual <= 0

    # actual의 값이 0과 -1 사이에 있는 경우 -1로 처리
    actual[(actual <= 0) & (actual > -1)] = -1
    
    # 양수 및 음수 값의 개수
    n1 = np.sum(positive_index) + 1e-3  # 작은 값으로 설정
    n2 = np.sum(negative_index) + 1e-3

    # e1: 양수 가격 예측 오차율
    e1 = (
        np.sum(
            np.abs(actual[positive_index] - forecast[positive_index])
            / np.maximum(np.abs(actual[positive_index]), 1e-3)  # 작은 값으로 분모 안정화
        )
        / n1
    )

    # e2: 음수 가격 예측 오차율
    e2 = (
        np.sum(
            np.abs(actual[negative_index] - forecast[negative_index])
            / np.maximum(np.abs(actual[negative_index]), 1e-3)
        )
        / n2
    )

    TP = np.sum((forecast > 0) & (actual > 0))
    TN = np.sum((forecast <= 0) & (actual <= 0))
    FP = np.sum((forecast > 0) & (actual <= 0))
    FN = np.sum((forecast <= 0) & (actual > 0))

    # 정확도 계산
    Accuracy = (TP + TN) / (TP + TN + FP + FN)
    e_F = 0.2 * e1 + 0.8 * e2 - (Accuracy - 0.95)

    return e_F

# e_F 값 계산
e_F_value = calculate_measure(actual, forecast)
print("e_F value:", e_F_value)

In [ ]:
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import pandas as pd
import platform

# 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':  # MacOS
    plt.rcParams['font.family'] = 'AppleGothic'
else:  # Linux
    plt.rcParams['font.family'] = 'NanumGothic'
    
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 부호 깨짐 방지

# 타임스탬프를 datetime 형식으로 변환
df_23day['datetime'] = pd.to_datetime(df_23day['ts'], unit='s')
smp_rt_rc_df['datetime'] = pd.to_datetime(smp_rt_rc_df['ts'], unit='s')

# 예측 데이터와 실제 데이터 준비
predicted_values = df_23day['smp_da']
actual_values = smp_rt_rc_df['실시간 확정 가격(원/kWh)']
time_stamps = df_23day['datetime']  # datetime으로 변환된 타임스탬프

# 그래프 생성
plt.figure(figsize=(12, 6))
plt.plot(time_stamps, predicted_values, label='Predicted Values', color='blue', linestyle='--', linewidth=1.5)
plt.plot(time_stamps, actual_values, label='Actual Values', color='red', linestyle='-', linewidth=1.5)
plt.xlabel('Time')
plt.ylabel('Price (원/kWh)')
plt.title('Predicted vs Actual Electricity Prices on 23rd')
plt.legend()
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
import json
import requests

result = {
    'submit_result': predictions.tolist() 
}

success = requests.post(
    'https://research-api.solarkim.com/submissions/cmpt-2024',
    data=json.dumps(result),
    headers={
        'Authorization': f'Bearer {"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"}'
    }
).json()

print(success)

In [3]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
response = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/actual-weather/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()


actual_weather_data = response['actual_weather_1']
actual_weather_df = pd.DataFrame(actual_weather_data)
actual_weather_df

,ts,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,uv_idx,vis,cld_cvr,ceiling,pressure,appr_temp,wind_chill_temp,wet_bulb_temp,precip_1h,location
0,1729609320,19.9,16.6,16.6,83.0,16.9,315.0,28.1,47.8,0.0,14.5,77.0,579.0,1013.2,20.0,20.0,18.0,0.1,Ilgwa-ri
1,1729612920,19.6,16.9,16.9,80.0,16.0,315.0,24.9,63.0,0.0,22.5,83.0,1798.0,1013.5,20.0,19.4,17.4,0.1,Ilgwa-ri
2,1729616160,18.8,16.0,16.0,79.0,15.2,315.0,25.9,58.0,0.0,16.1,68.0,1798.0,1016.0,20.0,18.9,16.7,0.0,Ilgwa-ri
3,1729616520,19.3,16.5,16.5,77.0,15.2,315.0,25.9,58.0,0.0,16.1,68.0,579.0,1013.9,19.4,19.4,16.8,0.0,Ilgwa-ri
4,1729619760,18.6,16.4,16.4,73.0,13.8,315.0,26.3,48.7,0.0,16.1,78.0,1798.0,1016.0,19.4,18.3,15.8,0.0,Ilgwa-ri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,1729684920,17.0,13.6,13.6,76.0,12.8,338.0,32.4,32.4,0.0,16.1,15.0,10150.0,1019.6,18.3,17.2,14.6,0.0,Sangmo-ri
269,1729688520,15.9,12.0,12.0,82.0,12.8,338.0,32.4,33.7,0.0,22.5,2.0,10180.0,1019.3,18.9,16.1,14.1,0.0,Sangmo-ri
270,1729691760,16.7,12.8,12.8,81.0,13.4,338.0,37.8,37.8,0.0,16.1,5.0,12192.0,1021.0,18.9,16.7,14.8,0.0,Sangmo-ri
271,1729692120,15.8,11.6,11.6,85.0,13.4,338.0,37.8,37.8,0.0,16.1,5.0,10150.0,1019.0,18.9,15.6,14.4,0.0,Sangmo-ri
272,1729695360,16.5,12.6,12.6,82.0,13.4,23.0,37.5,37.5,0.0,16.1,15.0,12192.0,1021.0,18.9,16.7,14.7,0.0,Sangmo-ri

In [4]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
response = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/weather-forecast/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()

weather_forecast_data = response['weather_forecast_1']
weather_forecast_df = pd.DataFrame(weather_forecast_data)
weather_forecast_df

,base_ts,ts,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_spd,wind_dir,wind_gust_spd,rel_hum,...,precip_prob,rain_prob,snow_prob,ice_prob,total_liq,rain,snow,ice,cld_cvr,location
0,1729648800,1729695600,16.6667,13.8889,13.8889,11.1111,20.4387,11.0,42.6476,71.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,Ilgwa-ri
1,1729648800,1729699200,16.6667,13.8889,13.3333,11.1111,20.4387,11.0,42.6476,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,Ilgwa-ri
2,1729648800,1729702800,16.1111,13.8889,13.3333,11.1111,22.2089,9.0,44.4179,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,Ilgwa-ri
3,1729648800,1729706400,16.1111,13.3333,13.3333,11.1111,22.2089,8.0,44.4179,72.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,Ilgwa-ri
4,1729648800,1729710000,16.1111,13.3333,13.3333,11.1111,22.2089,9.0,44.4179,73.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,Ilgwa-ri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,1729648800,1729767600,19.4444,17.7778,14.4444,10.5556,13.0357,345.0,16.7372,57.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sangmo-ri
221,1729648800,1729771200,19.4444,17.7778,14.4444,10.5556,13.0357,325.0,16.7372,57.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sangmo-ri
222,1729648800,1729774800,18.8889,17.2222,14.4444,11.1111,13.0357,356.0,16.7372,59.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sangmo-ri
223,1729648800,1729778400,18.3333,16.6667,14.4444,11.1111,13.0357,69.0,16.7372,63.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sangmo-ri
224,1729648800,1729782000,19.4444,17.7778,15.0000,11.6667,13.0357,83.0,18.5075,61.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sangmo-ri

In [5]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
smp_da = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/smp-da/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()
smp_da_df = pd.DataFrame(smp_da)
smp_da_df

            ts  smp_da
0   1729612800  219.19
1   1729616400  209.55
2   1729620000    0.00
3   1729623600    0.00
4   1729627200    0.00
5   1729630800    0.00
6   1729634400  205.18
7   1729638000  205.91
8   1729641600  200.40
9   1729645200    0.00
10  1729648800    0.00
11  1729652400  -48.00
12  1729656000    0.00
13  1729659600    0.00
14  1729663200    0.00
15  1729666800  206.85
16  1729670400  134.74
17  1729674000  139.60
18  1729677600  153.64
19  1729681200  134.75
20  1729684800  133.20
21  1729688400  106.56
22  1729692000  214.43
23  1729695600  155.28

In [6]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
smp_rt_rc = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/smp-rt-rc/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()
smp_rt_rc_df = pd.DataFrame(smp_rt_rc)
smp_rt_rc_df

            ts  smp_rt  smp_rc
0   1729612800  100.23  100.23
1   1729616400   92.35   92.35
2   1729620000   92.27   92.27
3   1729623600    0.00    0.00
4   1729627200    0.00    0.00
5   1729630800  100.25  100.25
6   1729634400  100.25  100.25
7   1729638000    0.00    0.00
8   1729641600  -48.00  -48.00
9   1729645200  -78.74  -78.74
10  1729648800  -78.74  -78.74
11  1729652400  -78.74  -78.74
12  1729656000  -78.74  -78.74
13  1729659600  -78.74  -78.74
14  1729663200  216.99  216.99
15  1729666800  134.74  134.74
16  1729670400  134.74  134.74
17  1729674000  139.60  139.60
18  1729677600  139.33  139.33
19  1729681200  134.75  134.75
20  1729684800  153.19  153.40
21  1729688400  106.56  106.56
22  1729692000  104.94  104.94
23  1729695600  105.29  105.29

In [7]:
import requests

date = '2024-10-23'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzI5NTgzOTkyLCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.2Y10TiejY2YYCZvaMP1k2F4Xl4m9aLQIHBd5yTwhnuA"
elec_supply = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/elec-supply/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()
elec_supply = pd.DataFrame(elec_supply)
elec_supply

,ts,supply_power,present_load,power_solar,power_wind,renewable_energy_total,supply_capacity,operation_capacity
0,1729609500,1254000.0,604000.0,0.0,252669.0,261110.0,644000.0,301000.0
1,1729609800,1260000.0,594000.0,0.0,254414.0,262771.0,661000.0,313000.0
2,1729610100,1258000.0,589000.0,0.0,253042.0,261438.0,664000.0,312000.0
3,1729610400,1245000.0,583000.0,0.0,239697.0,248055.0,657000.0,310000.0
4,1729610700,1243000.0,574000.0,0.0,235746.0,244142.0,665000.0,309000.0
...,...,...,...,...,...,...,...,...
282,1729694100,1134000.0,625000.0,0.0,144226.0,151880.0,505000.0,253000.0
283,1729694400,1147000.0,622000.0,0.0,156629.0,163462.0,520000.0,266000.0
284,1729694700,1152000.0,617000.0,0.0,161774.0,170022.0,530000.0,279000.0
285,1729695000,1151000.0,613000.0,0.0,159515.0,166246.0,534000.0,277000.0
286,1729695600,1170000.0,602000.0,0.0,178668.0,184943.0,564000.0,308000.0

In [8]:
weather_forecast_df = pd.get_dummies(weather_forecast_df, columns=['location'], prefix='location')
actual_weather_df = pd.get_dummies(actual_weather_df, columns=['location'], prefix='location')

display(weather_forecast_df)
display(actual_weather_df)

,base_ts,ts,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_spd,wind_dir,wind_gust_spd,rel_hum,...,cld_cvr,location_Bonggae-dong,location_Cheonji-dong,location_Geumak-ri,location_Gwangryeong-ri,location_Hacheon-ri,location_Ilgwa-ri,location_Sangmo-ri,location_Songdang-ri,location_Yongsu-ri
0,1729648800,1729695600,16.6667,13.8889,13.8889,11.1111,20.4387,11.0,42.6476,71.0,...,2.0,False,False,False,False,False,True,False,False,False
1,1729648800,1729699200,16.6667,13.8889,13.3333,11.1111,20.4387,11.0,42.6476,72.0,...,2.0,False,False,False,False,False,True,False,False,False
2,1729648800,1729702800,16.1111,13.8889,13.3333,11.1111,22.2089,9.0,44.4179,72.0,...,2.0,False,False,False,False,False,True,False,False,False
3,1729648800,1729706400,16.1111,13.3333,13.3333,11.1111,22.2089,8.0,44.4179,72.0,...,2.0,False,False,False,False,False,True,False,False,False
4,1729648800,1729710000,16.1111,13.3333,13.3333,11.1111,22.2089,9.0,44.4179,73.0,...,3.0,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,1729648800,1729767600,19.4444,17.7778,14.4444,10.5556,13.0357,345.0,16.7372,57.0,...,0.0,False,False,False,False,False,False,True,False,False
221,1729648800,1729771200,19.4444,17.7778,14.4444,10.5556,13.0357,325.0,16.7372,57.0,...,0.0,False,False,False,False,False,False,True,False,False
222,1729648800,1729774800,18.8889,17.2222,14.4444,11.1111,13.0357,356.0,16.7372,59.0,...,0.0,False,False,False,False,False,False,True,False,False
223,1729648800,1729778400,18.3333,16.6667,14.4444,11.1111,13.0357,69.0,16.7372,63.0,...,0.0,False,False,False,False,False,False,True,False,False
224,1729648800,1729782000,19.4444,17.7778,15.0000,11.6667,13.0357,83.0,18.5075,61.0,...,0.0,False,False,False,False,False,False,True,False,False

,ts,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,uv_idx,...,precip_1h,location_Bonggae-dong,location_Cheonji-dong,location_Geumak-ri,location_Gwangryeong-ri,location_Hacheon-ri,location_Ilgwa-ri,location_Sangmo-ri,location_Songdang-ri,location_Yongsu-ri
0,1729609320,19.9,16.6,16.6,83.0,16.9,315.0,28.1,47.8,0.0,...,0.1,False,False,False,False,False,True,False,False,False
1,1729612920,19.6,16.9,16.9,80.0,16.0,315.0,24.9,63.0,0.0,...,0.1,False,False,False,False,False,True,False,False,False
2,1729616160,18.8,16.0,16.0,79.0,15.2,315.0,25.9,58.0,0.0,...,0.0,False,False,False,False,False,True,False,False,False
3,1729616520,19.3,16.5,16.5,77.0,15.2,315.0,25.9,58.0,0.0,...,0.0,False,False,False,False,False,True,False,False,False
4,1729619760,18.6,16.4,16.4,73.0,13.8,315.0,26.3,48.7,0.0,...,0.0,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,1729684920,17.0,13.6,13.6,76.0,12.8,338.0,32.4,32.4,0.0,...,0.0,False,False,False,False,False,False,True,False,False
269,1729688520,15.9,12.0,12.0,82.0,12.8,338.0,32.4,33.7,0.0,...,0.0,False,False,False,False,False,False,True,False,False
270,1729691760,16.7,12.8,12.8,81.0,13.4,338.0,37.8,37.8,0.0,...,0.0,False,False,False,False,False,False,True,False,False
271,1729692120,15.8,11.6,11.6,85.0,13.4,338.0,37.8,37.8,0.0,...,0.0,False,False,False,False,False,False,True,False,False
272,1729695360,16.5,12.6,12.6,82.0,13.4,23.0,37.5,37.5,0.0,...,0.0,False,False,False,False,False,False,True,False,False

In [9]:
actual_weather_df['ts'] = actual_weather_df['ts'].astype('Int64')
smp_da_df['ts'] = smp_da_df['ts'].astype('Int64')
smp_rt_rc_df['ts'] = smp_rt_rc_df['ts'].astype('Int64')
elec_supply['ts'] = elec_supply['ts'].astype('Int64')
weather_forecast_df['base_ts'] = weather_forecast_df['base_ts'].astype('Int64')
weather_forecast_df['ts'] = weather_forecast_df['ts'].astype('Int64')

In [10]:
actual_weather_df = actual_weather_df.sort_values(by='ts').reset_index(drop=True)
smp_da_df = smp_da_df.sort_values(by='ts').reset_index(drop=True)
elec_supply = elec_supply.sort_values(by='ts').reset_index(drop=True)
weather_forecast_df = weather_forecast_df.sort_values(by='ts').reset_index(drop=True)

# 병합을 위한 기준 데이터프레임 설정
merged_data = smp_rt_rc_df.copy()

# 'ts'를 기준으로 가장 가까운 값을 병합
merged_data = pd.merge_asof(merged_data, actual_weather_df, on='ts', direction='nearest', suffixes=('', '_aw'))
merged_data = pd.merge_asof(merged_data, smp_da_df, on='ts', direction='nearest')
merged_data = pd.merge_asof(merged_data, elec_supply, on='ts', direction='nearest')
merged_data = pd.merge_asof(merged_data, weather_forecast_df, on='ts', direction='nearest', suffixes=('', '_wf'))

# 결과 확인
merged_data

,ts,smp_rt,smp_rc,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,...,cld_cvr_wf,location_Bonggae-dong_wf,location_Cheonji-dong_wf,location_Geumak-ri_wf,location_Gwangryeong-ri_wf,location_Hacheon-ri_wf,location_Ilgwa-ri_wf,location_Sangmo-ri_wf,location_Songdang-ri_wf,location_Yongsu-ri_wf
0,1729612800,100.23,100.23,19.4,16.3,16.3,79.0,15.7,113.0,20.2,...,2.0,False,False,False,False,False,True,False,False,False
1,1729616400,92.35,92.35,25.8,25.7,25.7,68.0,19.6,23.0,9.4,...,2.0,False,False,False,False,False,True,False,False,False
2,1729620000,92.27,92.27,16.3,13.4,13.4,91.0,14.8,293.0,18.7,...,2.0,False,False,False,False,False,True,False,False,False
3,1729623600,0.00,0.00,17.8,15.3,15.3,69.0,11.9,315.0,23.8,...,2.0,False,False,False,False,False,True,False,False,False
4,1729627200,0.00,0.00,18.1,14.9,14.9,63.0,11.0,225.0,20.2,...,2.0,False,False,False,False,False,True,False,False,False
5,1729630800,100.25,100.25,22.2,21.5,21.5,75.0,17.5,270.0,5.0,...,2.0,False,False,False,False,False,True,False,False,False
6,1729634400,100.25,100.25,16.4,13.3,13.3,70.0,10.9,315.0,28.5,...,2.0,False,False,False,False,False,True,False,False,False
7,1729638000,0.00,0.00,21.1,21.6,21.6,80.0,17.6,225.0,6.5,...,2.0,False,False,False,False,False,True,False,False,False
8,1729641600,-48.00,-48.00,17.2,17.3,16.2,64.0,10.5,68.0,10.8,...,2.0,False,False,False,False,False,True,False,False,False
9,1729645200,-78.74,-78.74,18.8,19.4,17.3,59.0,10.6,180.0,12.6,...,2.0,False,False,False,False,False,True,False,False,False
10,1729648800,-78.74,-78.74,19.0,17.6,16.6,57.0,10.4,315.0,28.5,...,2.0,False,False,False,False,False,True,False,False,False
11,1729652400,-78.74,-78.74,19.3,20.2,17.4,60.0,11.3,45.0,18.7,...,2.0,False,False,False,False,False,True,False,False,False
12,1729656000,-78.74,-78.74,18.0,15.2,14.6,57.0,9.4,315.0,38.9,...,2.0,False,False,False,False,False,True,False,False,False
13,1729659600,-78.74,-78.74,17.8,16.5,15.4,63.0,11.1,315.0,22.2,...,2.0,False,False,False,False,False,True,False,False,False
14,1729663200,216.99,216.99,16.5,14.8,13.2,68.0,10.6,315.0,28.8,...,2.0,False,False,False,False,False,True,False,False,False
15,1729666800,134.74,134.74,17.7,16.3,15.3,62.0,10.4,248.0,21.6,...,2.0,False,False,False,False,False,True,False,False,False
16,1729670400,134.74,134.74,17.9,17.7,17.7,68.0,11.9,158.0,8.6,...,2.0,False,False,False,False,False,True,False,False,False
17,1729674000,139.60,139.60,13.9,11.4,11.4,79.0,10.4,293.0,18.4,...,2.0,False,False,False,False,False,True,False,False,False
18,1729677600,139.33,139.33,20.6,19.1,19.1,55.0,11.2,158.0,11.1,...,2.0,False,False,False,False,False,True,False,False,False
19,1729681200,134.75,134.75,14.2,12.6,12.6,67.0,8.1,180.0,12.0,...,2.0,False,False,False,False,False,True,False,False,False
20,1729684800,153.19,153.40,17.0,13.6,13.6,76.0,12.8,338.0,32.4,...,2.0,False,False,False,False,False,True,False,False,False
21,1729688400,106.56,106.56,15.9,12.0,12.0,82.0,12.8,338.0,32.4,...,2.0,False,False,False,False,False,True,False,False,False
22,1729692000,104.94,104.94,15.8,11.6,11.6,85.0,13.4,338.0,37.8,...,2.0,False,False,False,False,False,True,False,False,False
23,1729695600,105.29,105.29,16.5,12.6,12.6,82.0,13.4,23.0,37.5,...,1.0,False,False,False,False,False,False,True,False,False