In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
import requests
import matplotlib.pyplot as plt

base_path =  'C:/Users/언종/Desktop/data'

# 각 데이터 파일 불러오기
weather_forecast_1 = pd.read_csv(f'{base_path}/기상예측데이터_1.csv')
weather_forecast_2 = pd.read_csv(f'{base_path}/기상예측데이터_2.csv')
weather_actual_1 = pd.read_csv(f'{base_path}/기상실측데이터_1.csv')
weather_actual_2 = pd.read_csv(f'{base_path}/기상실측데이터_2.csv')
price_day_ahead = pd.read_csv(f'{base_path}/제주전력시장_시장전기가격_하루전가격.csv')

In [2]:
price_day_ahead = price_day_ahead.rename(columns={
    '하루전가격(원/kWh)' : 'smp_da'
})

In [3]:
dates = ['2024-10-23', '2024-10-24', '2024-10-25', '2024-10-26', '2024-10-27',
         '2024-10-28', '2024-10-29','2024-10-30', '2024-10-31', '2024-11-01',
         '2024-11-02', '2024-11-03', '2024-11-04', '2024-11-05','2024-11-06',
         '2024-11-07','2024-11-08', '2024-11-09', '2024-11-10', '2024-11-11',
         '2024-11-12', '2024-11-13', '2024-11-14']

data_frames = []

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzMxMjAxMzE4LCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.1HewB2-rCsqpwLN4FlbwPOAOoIDK54phUZmcJorS2W4"
headers = {
    'Authorization': f'Bearer {token}'
}

for date in dates:
    response = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/smp-da/{date}', headers=headers)
    daily_data = response.json()
    daily_df = pd.DataFrame(daily_data)
    data_frames.append(daily_df)

smp_da_combined_df = pd.concat(data_frames, ignore_index=True)
smp_da_combined_df

             ts  smp_da
0    1729612800  219.19
1    1729616400  209.55
2    1729620000    0.00
3    1729623600    0.00
4    1729627200    0.00
..          ...     ...
547  1731582000  116.98
548  1731585600  126.24
549  1731589200  125.50
550  1731592800  106.52
551  1731596400  105.55

[552 rows x 2 columns]

# ***smp_da 제대로 안 불러와질때 돌리기***

import pandas as pd
from datetime import datetime, timedelta

ts = [datetime(2024, 11, 14, 1, 0) + timedelta(hours=i) for i in range(24)]

ts_unix = [int(dt.timestamp()) for dt in ts]

smp_da = [
     103.76, 87.57, 83.40, 85.30, 87.57, 102.76, 116.73, 116.73, 147.26,
        147.26, 147.26, 132.31, 132.31, 132.31, 147.26, 147.26, 147.26, 139.97,
        132.32, 116.98, 126.24, 125.50, 106.52, 105.55
]

k_df = pd.DataFrame({'ts': ts_unix, 'smp_da': smp_da})

k_df

smp_da_combined_df = pd.concat([smp_da_combined_df, k_df], ignore_index=True)
smp_da_combined_df

# ***여기부터***

In [4]:
dates = ['2024-10-23', '2024-10-24', '2024-10-25', '2024-10-26', '2024-10-27',
         '2024-10-28', '2024-10-29','2024-10-30', '2024-10-31', '2024-11-01',
         '2024-11-02', '2024-11-03', '2024-11-04', '2024-11-05','2024-11-06',
         '2024-11-07','2024-11-08', '2024-11-09', '2024-11-10', '2024-11-11',
         '2024-11-12', '2024-11-13', '2024-11-14']

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzMxMjAxMzE4LCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.1HewB2-rCsqpwLN4FlbwPOAOoIDK54phUZmcJorS2W4"
headers = {'Authorization': f'Bearer {token}'}

def fetch_data(endpoint, date):
    url = f'https://research-api.solarkim.com/data/cmpt-2024/{endpoint}/{date}'
    response = requests.get(url, headers=headers)
    return response.json()

actual_weather_1_dfs = []
actual_weather_2_dfs = []

for date in dates:
    data = fetch_data('actual-weather', date)
    actual_weather_1_dfs.append(pd.DataFrame(data['actual_weather_1']))
    actual_weather_2_dfs.append(pd.DataFrame(data['actual_weather_2']))

actual_weather_1_combined_df = pd.concat(actual_weather_1_dfs, ignore_index=True)
actual_weather_2_combined_df = pd.concat(actual_weather_2_dfs, ignore_index=True)

display(actual_weather_1_combined_df)
display(actual_weather_2_combined_df)

,ts,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,uv_idx,vis,cld_cvr,ceiling,pressure,appr_temp,wind_chill_temp,wet_bulb_temp,precip_1h,location
0,1729609320,19.9,16.6,16.6,83.0,16.9,315.0,28.1,47.8,0.0,14.5,77.0,579.0,1013.2,20.0,20.0,18.0,0.1,Ilgwa-ri
1,1729612920,19.6,16.9,16.9,80.0,16.0,315.0,24.9,63.0,0.0,22.5,83.0,1798.0,1013.5,20.0,19.4,17.4,0.1,Ilgwa-ri
2,1729616160,18.8,16.0,16.0,79.0,15.2,315.0,25.9,58.0,0.0,16.1,68.0,1798.0,1016.0,20.0,18.9,16.7,0.0,Ilgwa-ri
3,1729616520,19.3,16.5,16.5,77.0,15.2,315.0,25.9,58.0,0.0,16.1,68.0,579.0,1013.9,19.4,19.4,16.8,0.0,Ilgwa-ri
4,1729619760,18.6,16.4,16.4,73.0,13.8,315.0,26.3,48.7,0.0,16.1,78.0,1798.0,1016.0,19.4,18.3,15.8,0.0,Ilgwa-ri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5982,1731535320,17.5,13.7,13.7,74.0,12.7,90.0,31.7,31.7,0.0,22.5,79.0,3048.0,1021.3,18.3,17.2,14.8,0.1,Sangmo-ri
5983,1731538920,19.0,16.2,16.2,70.0,13.5,90.0,30.6,30.6,0.0,16.1,96.0,6096.0,1021.0,19.4,18.9,15.8,0.0,Sangmo-ri
5984,1731542160,19.3,17.5,16.9,69.0,13.6,90.0,30.3,30.3,1.0,16.1,45.0,12192.0,1020.0,19.4,19.4,16.0,0.0,Sangmo-ri
5985,1731542580,19.5,18.1,17.0,68.0,13.6,90.0,30.3,30.3,2.0,16.1,45.0,10363.0,1021.0,19.4,19.4,16.0,0.0,Sangmo-ri
5986,1731545880,20.0,18.2,17.4,68.0,13.9,90.0,34.6,34.6,2.0,22.5,74.0,10363.0,1021.0,19.4,20.0,16.4,0.0,Sangmo-ri

,ts,cloud,temp,temp_max,temp_min,humidity,ground_press,wind_speed,wind_dir,rain,snow,location
0,1729609282,100.0,20.25,20.25,20.25,84.0,1016.0,10.37,309.0,0.79,0.0,Gaigeturi
1,1729611047,75.0,20.03,20.03,20.03,77.0,1016.0,9.77,290.0,0.35,0.0,Gaigeturi
2,1729612873,100.0,20.32,20.32,20.32,76.0,1016.0,10.44,310.0,0.35,0.0,Gaigeturi
3,1729614646,75.0,19.03,19.03,19.03,82.0,1017.0,12.35,300.0,0.00,0.0,Gaigeturi
4,1729616465,100.0,19.99,19.99,19.99,75.0,1017.0,11.01,308.0,0.00,0.0,Gaigeturi
...,...,...,...,...,...,...,...,...,...,...,...,...
3229,1731540642,75.0,16.96,16.96,16.96,67.0,1021.0,5.14,100.0,0.00,0.0,Jeju
3230,1731542497,55.0,18.06,18.06,18.06,73.0,1021.0,6.60,104.0,0.00,0.0,Jeju
3231,1731544241,75.0,17.96,17.96,17.96,68.0,1020.0,6.69,90.0,0.00,0.0,Jeju
3232,1731546064,98.0,19.05,19.05,19.05,69.0,1020.0,5.96,105.0,0.00,0.0,Jeju
3233,1731547874,0.0,19.96,19.96,19.96,60.0,1020.0,6.69,80.0,0.00,0.0,Jeju

In [5]:
weather_actual_1 = pd.concat([weather_actual_1, actual_weather_1_combined_df], ignore_index=True)
weather_actual_2 = pd.concat([weather_actual_2, actual_weather_2_combined_df], ignore_index=True)
price_day_ahead = pd.concat([price_day_ahead, smp_da_combined_df], ignore_index=True)

In [6]:
def convert_columns(df):
    for col in df.columns:
        if col == 'ts' :
            df[col] = pd.to_numeric(df[col], errors='coerce').astype('Int64')  # ts는 Int64형으로 변환
        else:
            df[col] = pd.to_numeric(df[col], errors='coerce').astype(float)  # 나머지는 float형으로 변환
    return df  
    
weather_actual_1 = convert_columns(weather_actual_1)
weather_actual_2 = convert_columns(weather_actual_2)
price_day_ahead = convert_columns(price_day_ahead)

In [7]:
weather_actual_1 = weather_actual_1.drop(columns=['location'], errors='ignore')
weather_actual_2 = weather_actual_2.drop(columns=['location'], errors='ignore')

## ***이거는 실행 안 하는 코드 ↓***

threshold_ts =   1731460200

for df in [weather_actual_1, weather_actual_2]:
    df.drop(df[df['ts'] > threshold_ts].index, inplace=True)

## weather_actual_1에만 있는 칼럼: 
{'real_feel_temp_shade', 'wind_chill_temp', 'appr_temp', 'pressure', 'precip_1h'}

In [8]:
# 각 데이터 프레임에 대해 결측치가 포함된 행만 출력
dataframes = {
    "weather_actual_1": weather_actual_1,
    "weather_actual_2": weather_actual_2,
     "price_day_ahead": price_day_ahead
}

for name, df in dataframes.items():
    print(f"\nDataFrame: {name}")
    # 결측치가 있는 행만 선택
    missing_rows = df[df.isnull().any(axis=1)]
    display(missing_rows)

DataFrame: weather_actual_1

,ts,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,uv_idx,vis,cld_cvr,ceiling,pressure,appr_temp,wind_chill_temp,wet_bulb_temp,precip_1h
7933,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13959,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21944,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28133,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36827,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42840,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50575,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56810,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

DataFrame: weather_actual_2

,ts,cloud,temp,temp_max,temp_min,humidity,ground_press,wind_speed,wind_dir,rain,snow
11332,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22672,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

DataFrame: price_day_ahead

Empty DataFrame
Columns: [ts, smp_da]
Index: []

In [9]:
def drop_missing_rows(df):
    return df.dropna(subset=['ts'])

weather_actual_1 = drop_missing_rows(weather_actual_1)
weather_actual_2 = drop_missing_rows(weather_actual_2)
price_day_ahead = drop_missing_rows(price_day_ahead)

# weather_actual_1 리샘플링

In [10]:
weather_actual_1['datetime'] = pd.to_datetime(weather_actual_1['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')

weather_actual_1['datetime_rounded'] = weather_actual_1['datetime'].dt.round('H')

weather_actual_1 = weather_actual_1.drop(columns=['ts', 'datetime'])

weather_actual_1 = weather_actual_1.rename(columns={'datetime_rounded': 'ts'})
weather_actual_1 = weather_actual_1[['ts'] + [col for col in weather_actual_1.columns if col != 'ts']]

weather_actual_1['ts'] = weather_actual_1['ts'].dt.tz_convert('UTC').apply(lambda x: int(x.timestamp()))

weather_actual_1 = weather_actual_1.sort_values(by='ts').reset_index(drop=True)

average_duplicates = weather_actual_1[weather_actual_1.duplicated('ts', keep=False)]
average_duplicates = average_duplicates.groupby('ts', as_index=False).mean()

# 중복되지 않은 ts 값과 합치기
unique_values = weather_actual_1.drop_duplicates('ts', keep=False)

# 중복된 평균 값과 고유 값 결합 후 ts 기준 정렬
weather_actual_1 = pd.concat([unique_values, average_duplicates], ignore_index=True).sort_values('ts').reset_index(drop=True)

C:\Users\언종\AppData\Local\Temp\ipykernel_460\3617583132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_actual_1['datetime'] = pd.to_datetime(weather_actual_1['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')
C:\Users\언종\AppData\Local\Temp\ipykernel_460\3617583132.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  weather_actual_1['datetime_rounded'] = weather_actual_1['datetime'].dt.round('H')
C:\Users\언종\AppData\Local\Temp\ipykernel_460\3617583132.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_actual_1['datetime_rounded'] = weather_actual_1['datetime'].dt.round('H')

# weather_actual_2 리샘플링

In [11]:
weather_actual_2['datetime'] = pd.to_datetime(weather_actual_2['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')

weather_actual_2['datetime_rounded'] = weather_actual_2['datetime'].dt.round('H')

weather_actual_2 = weather_actual_2.drop(columns=['ts', 'datetime'])

weather_actual_2 = weather_actual_2.rename(columns={'datetime_rounded': 'ts'})
weather_actual_2 = weather_actual_2[['ts'] + [col for col in weather_actual_2.columns if col != 'ts']]

weather_actual_2['ts'] = weather_actual_2['ts'].dt.tz_convert('UTC').apply(lambda x: int(x.timestamp()))

weather_actual_2 = weather_actual_2.sort_values(by='ts').reset_index(drop=True)

average_duplicates = weather_actual_2[weather_actual_2.duplicated('ts', keep=False)]
average_duplicates = average_duplicates.groupby('ts', as_index=False).mean()

# 중복되지 않은 ts 값과 합치기
unique_values = weather_actual_2.drop_duplicates('ts', keep=False)

# 중복된 평균 값과 고유 값 결합 후 ts 기준 정렬
weather_actual_2 = pd.concat([unique_values, average_duplicates], ignore_index=True).sort_values('ts').reset_index(drop=True)

C:\Users\언종\AppData\Local\Temp\ipykernel_460\1512181384.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_actual_2['datetime'] = pd.to_datetime(weather_actual_2['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')
C:\Users\언종\AppData\Local\Temp\ipykernel_460\1512181384.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  weather_actual_2['datetime_rounded'] = weather_actual_2['datetime'].dt.round('H')
C:\Users\언종\AppData\Local\Temp\ipykernel_460\1512181384.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  weather_actual_2['datetime_rounded'] = weather_actual_2['datetime'].dt.round('H')

In [12]:
dataframes = [
    weather_actual_1,
    weather_actual_2
]

merged_df = price_day_ahead.copy()

for df in dataframes:
    df = df.drop_duplicates(subset=['ts'])

    merged_df = pd.merge(merged_df, df, on='ts', how='left', suffixes=('', '_dup'))

    for column in df.columns:
        if column != 'ts' and column in merged_df.columns and f"{column}_dup" in merged_df.columns:
            merged_df[column] = merged_df[[column, f"{column}_dup"]].mean(axis=1)
            merged_df.drop(columns=[f"{column}_dup"], inplace=True)

print(merged_df.shape)
display(merged_df)

(6217, 27)

,ts,smp_da,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,...,wet_bulb_temp,precip_1h,cloud,temp_max,temp_min,humidity,ground_press,wind_speed,rain,snow
0,1709218800,107.39,7.323333,8.000000,8.000000,81.000000,5.500000,307.666667,6.100000,17.600000,...,7.100000,0.100000,89.333333,6.146667,6.146667,74.666667,1022.666667,8.553333,0.17,0.0
1,1709222400,107.39,6.706667,3.041667,3.041667,72.666667,2.508333,288.333333,20.483333,26.366667,...,5.091667,0.008333,83.500000,6.255000,6.255000,70.500000,1022.500000,6.256667,0.00,0.0
2,1709226000,95.30,6.202222,2.111111,2.111111,75.666667,2.433333,302.944444,21.944444,27.433333,...,4.733333,0.011111,84.333333,5.926667,5.926667,67.833333,1022.833333,7.291667,0.21,0.0
3,1709229600,87.89,5.621894,0.900000,0.900000,74.545455,1.663636,277.666667,22.490909,27.645455,...,4.209091,0.136364,83.666667,5.198333,5.198333,63.833333,1023.500000,7.520000,0.00,0.0
4,1709233200,0.00,4.931667,-0.090000,-0.090000,68.100000,-0.030000,299.400000,26.140000,42.440000,...,3.180000,0.410000,42.166667,4.433333,4.433333,64.833333,1023.833333,7.330000,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6212,1731582000,116.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6213,1731585600,126.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6214,1731589200,125.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6215,1731592800,106.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6216,1731596400,105.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
missing_rows = merged_df[merged_df.isna().any(axis=1)]
missing_rows

,ts,smp_da,temp,real_feel_temp,real_feel_temp_shade,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,...,wet_bulb_temp,precip_1h,cloud,temp_max,temp_min,humidity,ground_press,wind_speed,rain,snow
6203,1731549600,147.26,18.65,NaN,NaN,NaN,NaN,80.0,NaN,NaN,...,NaN,NaN,0.0,18.65,18.65,60.0,1020.0,6.69,0.0,0.0
6204,1731553200,132.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6205,1731556800,132.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6206,1731560400,132.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6207,1731564000,147.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6208,1731567600,147.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6209,1731571200,147.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6210,1731574800,139.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6211,1731578400,132.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6212,1731582000,116.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6213,1731585600,126.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6214,1731589200,125.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6215,1731592800,106.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6216,1731596400,105.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# ***예측날씨로 못채워주는 칼럼 날리기***

In [14]:
columns_to_drop = ['appr_temp', 'pressure',
                   'real_feel_temp_shade', 'wind_chill_temp', 'precip_1h']

merged_df = merged_df.drop(columns=columns_to_drop)

In [15]:
missing_rows = merged_df[merged_df.isna().any(axis=1)]
missing_rows

,ts,smp_da,temp,real_feel_temp,rel_hum,dew_point,wind_dir,wind_spd,wind_gust_spd,uv_idx,...,ceiling,wet_bulb_temp,cloud,temp_max,temp_min,humidity,ground_press,wind_speed,rain,snow
6203,1731549600,147.26,18.65,NaN,NaN,NaN,80.0,NaN,NaN,NaN,...,NaN,NaN,0.0,18.65,18.65,60.0,1020.0,6.69,0.0,0.0
6204,1731553200,132.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6205,1731556800,132.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6206,1731560400,132.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6207,1731564000,147.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6208,1731567600,147.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6209,1731571200,147.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6210,1731574800,139.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6211,1731578400,132.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6212,1731582000,116.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6213,1731585600,126.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6214,1731589200,125.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6215,1731592800,106.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6216,1731596400,105.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# ***살제날씨가 못채우는 정보 예측날씨로 채워주기***

In [16]:
dates = ['2024-11-13']
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzMxMjAxMzE4LCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.1HewB2-rCsqpwLN4FlbwPOAOoIDK54phUZmcJorS2W4"
headers = {'Authorization': f'Bearer {token}'}

def fetch_data(endpoint, date):
    url = f'https://research-api.solarkim.com/data/cmpt-2024/{endpoint}/{date}'
    response = requests.get(url, headers=headers)
    return response.json()

weather_forecast_1_dfs = []
weather_forecast_2_dfs = []

for date in dates:
    data = fetch_data('weather-forecast', date)
    weather_forecast_1_dfs.append(pd.DataFrame(data['weather_forecast_1']))
    weather_forecast_2_dfs.append(pd.DataFrame(data['weather_forecast_2']))

weather_forecast_1_combined_df = pd.concat(weather_forecast_1_dfs, ignore_index=True)
weather_forecast_2_combined_df = pd.concat(weather_forecast_2_dfs, ignore_index=True)

display(weather_forecast_1_combined_df)
display(weather_forecast_2_combined_df)

,base_ts,ts,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_spd,wind_dir,wind_gust_spd,rel_hum,...,precip_prob,rain_prob,snow_prob,ice_prob,total_liq,rain,snow,ice,cld_cvr,location
0,1731463200,1731510000,17.7778,16.1111,15.5556,13.3333,18.5075,88.0,25.9104,75.0,...,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,15.0,Ilgwa-ri
1,1731463200,1731513600,17.7778,15.5556,15.0000,13.3333,18.5075,87.0,25.9104,75.0,...,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,30.0,Ilgwa-ri
2,1731463200,1731517200,17.7778,15.5556,15.0000,12.7778,18.5075,84.0,25.9104,74.0,...,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,45.0,Ilgwa-ri
3,1731463200,1731520800,17.2222,15.5556,15.0000,12.7778,18.5075,82.0,27.8417,74.0,...,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,61.0,Ilgwa-ri
4,1731463200,1731524400,17.2222,15.5556,14.4444,12.2222,18.5075,82.0,27.8417,73.0,...,0.0,0.0,0.0,0.0,0.000,0.000,0.0,0.0,48.0,Ilgwa-ri
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,1731463200,1731582000,20.5556,18.8889,17.7778,16.1111,14.8060,99.0,22.2089,75.0,...,14.0,14.0,0.0,0.0,0.000,0.000,0.0,0.0,70.0,Sangmo-ri
221,1731463200,1731585600,20.5556,18.8889,17.7778,16.6667,16.7372,102.0,22.2089,77.0,...,18.0,18.0,0.0,0.0,0.000,0.000,0.0,0.0,58.0,Sangmo-ri
222,1731463200,1731589200,20.0000,18.8889,17.7778,16.6667,16.7372,105.0,20.4387,79.0,...,49.0,49.0,0.0,0.0,0.000,0.000,0.0,0.0,71.0,Sangmo-ri
223,1731463200,1731592800,20.5556,18.3333,18.3333,16.6667,18.5075,110.0,20.4387,79.0,...,51.0,51.0,0.0,0.0,0.000,0.000,0.0,0.0,84.0,Sangmo-ri
224,1731463200,1731596400,20.5556,17.2222,18.3333,16.6667,18.5075,118.0,20.4387,80.0,...,56.0,56.0,0.0,0.0,1.016,1.016,0.0,0.0,98.0,Sangmo-ri

,base_ts,ts,cloud,temp,temp_max,temp_min,humidity,ground_press,wind_speed,wind_dir,rain,snow,location
0,1731463200,1731510000,10.0,17.83,17.83,17.83,69.0,1022.0,6.13,94.0,0.0,0.0,Gaigeturi
1,1731463200,1731513600,10.0,17.63,17.63,17.63,70.0,1021.0,6.11,92.0,0.0,0.0,Gaigeturi
2,1731463200,1731517200,10.0,17.42,17.42,17.42,70.0,1021.0,5.99,91.0,0.0,0.0,Gaigeturi
3,1731463200,1731520800,11.0,17.22,17.22,17.22,71.0,1021.0,5.71,93.0,0.0,0.0,Gaigeturi
4,1731463200,1731524400,13.0,17.02,17.02,17.02,71.0,1020.0,5.53,98.0,0.0,0.0,Gaigeturi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1731463200,1731582000,77.0,18.78,18.78,18.78,77.0,1019.0,1.90,146.0,0.0,0.0,Jeju
71,1731463200,1731585600,81.0,18.69,18.69,18.69,78.0,1020.0,0.92,139.0,0.0,0.0,Jeju
72,1731463200,1731589200,100.0,18.67,18.67,18.67,78.0,1019.0,1.84,130.0,0.0,0.0,Jeju
73,1731463200,1731592800,100.0,18.66,18.66,18.66,78.0,1019.0,1.26,127.0,0.0,0.0,Jeju
74,1731463200,1731596400,100.0,18.61,18.61,18.61,79.0,1019.0,1.91,94.0,0.0,0.0,Jeju

In [17]:
weather_forecast_1 = pd.concat([weather_forecast_1, weather_forecast_1_combined_df], ignore_index=True)
weather_forecast_2 = pd.concat([weather_forecast_2, weather_forecast_2_combined_df], ignore_index=True)

weather_forecast_1 = convert_columns(weather_forecast_1)
weather_forecast_2 = convert_columns(weather_forecast_2)

weather_forecast_1 = weather_forecast_1.drop(columns=['location'], errors='ignore')
weather_forecast_2 = weather_forecast_2.drop(columns=['location'], errors='ignore')

weather_forecast_1 = weather_forecast_1.drop(columns=['base_ts'], errors='ignore')
weather_forecast_2 = weather_forecast_2.drop(columns=['base_ts'], errors='ignore')

weather_forecast_1 = drop_missing_rows(weather_forecast_1)
weather_forecast_2 = drop_missing_rows(weather_forecast_2)

weather_forecast_1 = weather_forecast_1.groupby('ts').mean().reset_index()
weather_forecast_2 = weather_forecast_2.groupby('ts').mean().reset_index()

In [18]:
def merge_weather_data(df1, df2):
    # 데이터 병합 (outer join) 후 동일한 열 이름의 평균 계산
    forecast_df = pd.merge(df1, df2, on='ts', how='outer')
    
    # 동일한 열 이름에 대해 평균을 계산
    for col in df1.columns:
        if col != 'ts' and col in df2.columns:
            forecast_df[col] = forecast_df[[f"{col}_x", f"{col}_y"]].mean(axis=1)
            forecast_df.drop([f"{col}_x", f"{col}_y"], axis=1, inplace=True)
    
    return forecast_df

forecast_df = merge_weather_data(weather_forecast_1, weather_forecast_2)
forecast_df

,ts,real_feel_temp,wet_bulb_temp,dew_point,wind_spd,wind_gust_spd,rel_hum,vis,ceiling,uv_idx,...,cloud,temp_max,temp_min,humidity,ground_press,wind_speed,temp,wind_dir,rain,snow
0,1709305200,-4.320987,-0.555556,-4.320987,22.048022,50.604944,64.333333,16.093400,1700.106667,0.0,...,100.000000,1.213333,1.213333,60.333333,1027.000000,8.306667,1.470864,333.944444,0.000000,0.0
1,1709308800,-4.506173,-0.432099,-4.135800,22.048022,50.640711,64.333333,15.378140,1249.680000,0.0,...,100.000000,1.280000,1.280000,61.000000,1027.000000,8.043333,1.565926,334.333333,0.028222,0.0
2,1709312400,-5.061728,-0.370370,-3.950616,22.656000,51.481144,66.333333,14.392882,1229.360000,0.0,...,100.000000,1.323333,1.323333,60.666667,1026.666667,7.626667,1.556728,333.722222,0.098778,0.0
3,1709316000,-5.308640,-0.370370,-3.888887,23.263967,51.463267,67.333333,15.195758,1933.786667,0.0,...,100.000000,1.323333,1.323333,60.666667,1026.000000,7.310000,1.464136,333.222222,0.042333,0.0
4,1709319600,-4.876541,-0.308642,-3.950616,23.871922,50.837400,66.444444,15.825200,2600.960000,0.0,...,96.333333,1.356667,1.356667,60.666667,1026.000000,7.076667,1.604260,332.777778,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5709,1731582000,17.530867,16.604956,15.246911,12.159511,17.953144,78.777778,9.656060,8192.346667,0.0,...,76.000000,17.766667,17.766667,75.000000,1019.000000,1.583333,18.327789,131.055556,0.014111,0.0
5710,1731585600,17.839500,17.160500,15.493833,12.374089,17.112711,77.555556,9.656060,6289.040000,0.0,...,80.000000,17.703333,17.703333,75.333333,1019.666667,0.913333,18.573889,136.277778,0.028222,0.0
5711,1731589200,18.024700,17.283956,15.617300,13.393344,15.682189,78.444444,9.656060,3596.640000,0.0,...,100.000000,17.680000,17.680000,75.666667,1019.333333,1.796667,18.562222,121.611111,0.000000,0.0
5712,1731592800,17.654322,17.222211,15.802489,14.412600,16.111344,80.111111,8.761982,579.120000,0.0,...,100.000000,17.680000,17.680000,76.000000,1019.000000,1.303333,18.438772,113.722222,0.000000,0.0
5713,1731596400,17.716044,17.469133,15.925944,15.038456,16.486856,80.000000,8.225536,579.120000,0.0,...,100.000000,17.630000,17.630000,77.000000,1018.666667,2.400000,18.568089,104.888889,0.070556,0.0

In [19]:
forecast_df = forecast_df.drop(columns=['ice', 'snow_prob', 'ice_prob','rain_prob', 'total_liq'])

# ***merged_df의 결측치 예측날씨로 채워주기***

In [20]:
merged_df = merged_df.set_index('ts')
forecast_df = forecast_df.set_index('ts')

merged_df = merged_df.combine_first(forecast_df).reset_index()

merged_df = merged_df.drop(columns=['snow'])

merged_df

,ts,ceiling,cld_cvr,cloud,dew_point,ground_press,humidity,precip_prob,rain,real_feel_temp,...,temp,temp_max,temp_min,uv_idx,vis,wet_bulb_temp,wind_dir,wind_gust_spd,wind_spd,wind_speed
0,1709218800,579.000000,91.000000,89.333333,5.500000,1022.666667,74.666667,NaN,0.170000,8.000000,...,7.323333,6.146667,6.146667,0.0,20.900000,7.100000,307.666667,17.600000,6.100000,8.553333
1,1709222400,693.416667,97.750000,83.500000,2.508333,1022.500000,70.500000,NaN,0.000000,3.041667,...,6.706667,6.255000,6.255000,0.0,20.783333,5.091667,288.333333,26.366667,20.483333,6.256667
2,1709226000,616.222222,86.333333,84.333333,2.433333,1022.833333,67.833333,NaN,0.210000,2.111111,...,6.202222,5.926667,5.926667,0.0,20.033333,4.733333,302.944444,27.433333,21.944444,7.291667
3,1709229600,8692.363636,62.818182,83.666667,1.663636,1023.500000,63.833333,NaN,0.000000,0.900000,...,5.621894,5.198333,5.198333,0.0,19.900000,4.209091,277.666667,27.645455,22.490909,7.520000
4,1709233200,10911.800000,38.100000,42.166667,-0.030000,1023.833333,64.833333,NaN,0.000000,-0.090000,...,4.931667,4.433333,4.433333,0.0,23.800000,3.180000,299.400000,42.440000,26.140000,7.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6212,1731582000,8192.346667,54.888889,76.000000,15.246911,1019.000000,75.000000,13.444444,0.014111,17.530867,...,18.327789,17.766667,17.766667,0.0,9.656060,16.604956,131.055556,17.953144,12.159511,1.583333
6213,1731585600,6289.040000,57.000000,80.000000,15.493833,1019.666667,75.333333,14.888889,0.028222,17.839500,...,18.573889,17.703333,17.703333,0.0,9.656060,17.160500,136.277778,17.112711,12.374089,0.913333
6214,1731589200,3596.640000,68.333333,100.000000,15.617300,1019.333333,75.666667,17.888889,0.000000,18.024700,...,18.562222,17.680000,17.680000,0.0,9.656060,17.283956,121.611111,15.682189,13.393344,1.796667
6215,1731592800,579.120000,77.222222,100.000000,15.802489,1019.000000,76.000000,19.222222,0.000000,17.654322,...,18.438772,17.680000,17.680000,0.0,8.761982,17.222211,113.722222,16.111344,14.412600,1.303333
6216,1731596400,579.120000,89.333333,100.000000,15.925944,1018.666667,77.000000,21.111111,0.070556,17.716044,...,18.568089,17.630000,17.630000,0.0,8.225536,17.469133,104.888889,16.486856,15.038456,2.400000

In [21]:
missing_rows = merged_df[merged_df.isna().any(axis=1)]
missing_rows

,ts,ceiling,cld_cvr,cloud,dew_point,ground_press,humidity,precip_prob,rain,real_feel_temp,...,temp,temp_max,temp_min,uv_idx,vis,wet_bulb_temp,wind_dir,wind_gust_spd,wind_spd,wind_speed
0,1709218800,579.000000,91.000000,89.333333,5.500000,1022.666667,74.666667,NaN,0.17,8.000000,...,7.323333,6.146667,6.146667,0.0,20.900000,7.100000,307.666667,17.600000,6.100000,8.553333
1,1709222400,693.416667,97.750000,83.500000,2.508333,1022.500000,70.500000,NaN,0.00,3.041667,...,6.706667,6.255000,6.255000,0.0,20.783333,5.091667,288.333333,26.366667,20.483333,6.256667
2,1709226000,616.222222,86.333333,84.333333,2.433333,1022.833333,67.833333,NaN,0.21,2.111111,...,6.202222,5.926667,5.926667,0.0,20.033333,4.733333,302.944444,27.433333,21.944444,7.291667
3,1709229600,8692.363636,62.818182,83.666667,1.663636,1023.500000,63.833333,NaN,0.00,0.900000,...,5.621894,5.198333,5.198333,0.0,19.900000,4.209091,277.666667,27.645455,22.490909,7.520000
4,1709233200,10911.800000,38.100000,42.166667,-0.030000,1023.833333,64.833333,NaN,0.00,-0.090000,...,4.931667,4.433333,4.433333,0.0,23.800000,3.180000,299.400000,42.440000,26.140000,7.330000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6187,1731492000,9970.222222,20.111111,20.000000,11.666667,1021.000000,69.166667,NaN,0.00,16.988889,...,17.529167,16.891667,16.891667,0.0,24.122222,14.433333,99.500000,19.611111,12.588889,5.311667
6188,1731495600,9598.100000,18.600000,18.666667,11.530000,1021.666667,69.166667,NaN,0.00,16.020000,...,16.930833,16.721667,16.721667,0.0,19.640000,13.940000,103.616667,18.580000,12.950000,5.155000
6189,1731499200,8519.200000,18.600000,20.333333,11.550000,1022.000000,66.000000,NaN,0.00,16.690000,...,17.416667,16.803333,16.803333,0.0,19.800000,14.320000,103.666667,18.700000,13.360000,4.886667
6190,1731502800,10004.111111,22.888889,6.666667,10.944444,1021.666667,67.833333,NaN,0.00,16.366667,...,16.921944,16.221667,16.221667,0.0,24.122222,13.811111,97.583333,18.644444,12.422222,5.256667
6191,1731506400,10734.363636,22.636364,7.666667,11.863636,1021.666667,66.166667,NaN,0.00,16.409091,...,17.235379,16.661667,16.661667,0.0,22.690909,14.400000,95.969697,21.345455,13.109091,5.571667

In [22]:
missing_columns = merged_df.columns[merged_df.isnull().any()].tolist()

print("결측치가 있는 칼럼들:")
print(missing_columns)

결측치가 있는 칼럼들:
['precip_prob']

In [23]:
merged_df['datetime'] = pd.to_datetime(merged_df['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')

In [24]:
columns_to_fill = ['precip_prob']

for col in columns_to_fill:
    for i in merged_df.index:
        if pd.isna(merged_df.loc[i, col]):
            current_time = merged_df.loc[i, 'datetime']
            
            previous_day_time = current_time - pd.Timedelta(days=1)
            
            previous_day_data = merged_df[merged_df['datetime'] == previous_day_time]
            
            if not previous_day_data.empty:
                merged_df.loc[i, col] = previous_day_data[col].values[0]

merged_df

,ts,ceiling,cld_cvr,cloud,dew_point,ground_press,humidity,precip_prob,rain,real_feel_temp,...,temp_max,temp_min,uv_idx,vis,wet_bulb_temp,wind_dir,wind_gust_spd,wind_spd,wind_speed,datetime
0,1709218800,579.000000,91.000000,89.333333,5.500000,1022.666667,74.666667,NaN,0.170000,8.000000,...,6.146667,6.146667,0.0,20.900000,7.100000,307.666667,17.600000,6.100000,8.553333,2024-03-01 00:00:00+09:00
1,1709222400,693.416667,97.750000,83.500000,2.508333,1022.500000,70.500000,NaN,0.000000,3.041667,...,6.255000,6.255000,0.0,20.783333,5.091667,288.333333,26.366667,20.483333,6.256667,2024-03-01 01:00:00+09:00
2,1709226000,616.222222,86.333333,84.333333,2.433333,1022.833333,67.833333,NaN,0.210000,2.111111,...,5.926667,5.926667,0.0,20.033333,4.733333,302.944444,27.433333,21.944444,7.291667,2024-03-01 02:00:00+09:00
3,1709229600,8692.363636,62.818182,83.666667,1.663636,1023.500000,63.833333,NaN,0.000000,0.900000,...,5.198333,5.198333,0.0,19.900000,4.209091,277.666667,27.645455,22.490909,7.520000,2024-03-01 03:00:00+09:00
4,1709233200,10911.800000,38.100000,42.166667,-0.030000,1023.833333,64.833333,NaN,0.000000,-0.090000,...,4.433333,4.433333,0.0,23.800000,3.180000,299.400000,42.440000,26.140000,7.330000,2024-03-01 04:00:00+09:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6212,1731582000,8192.346667,54.888889,76.000000,15.246911,1019.000000,75.000000,13.444444,0.014111,17.530867,...,17.766667,17.766667,0.0,9.656060,16.604956,131.055556,17.953144,12.159511,1.583333,2024-11-14 20:00:00+09:00
6213,1731585600,6289.040000,57.000000,80.000000,15.493833,1019.666667,75.333333,14.888889,0.028222,17.839500,...,17.703333,17.703333,0.0,9.656060,17.160500,136.277778,17.112711,12.374089,0.913333,2024-11-14 21:00:00+09:00
6214,1731589200,3596.640000,68.333333,100.000000,15.617300,1019.333333,75.666667,17.888889,0.000000,18.024700,...,17.680000,17.680000,0.0,9.656060,17.283956,121.611111,15.682189,13.393344,1.796667,2024-11-14 22:00:00+09:00
6215,1731592800,579.120000,77.222222,100.000000,15.802489,1019.000000,76.000000,19.222222,0.000000,17.654322,...,17.680000,17.680000,0.0,8.761982,17.222211,113.722222,16.111344,14.412600,1.303333,2024-11-14 23:00:00+09:00
6216,1731596400,579.120000,89.333333,100.000000,15.925944,1018.666667,77.000000,21.111111,0.070556,17.716044,...,17.630000,17.630000,0.0,8.225536,17.469133,104.888889,16.486856,15.038456,2.400000,2024-11-15 00:00:00+09:00

In [25]:
missing_rows = merged_df[merged_df.isna().any(axis=1)]
missing_rows

,ts,ceiling,cld_cvr,cloud,dew_point,ground_press,humidity,precip_prob,rain,real_feel_temp,...,temp_max,temp_min,uv_idx,vis,wet_bulb_temp,wind_dir,wind_gust_spd,wind_spd,wind_speed,datetime
0,1709218800,579.000000,91.000000,89.333333,5.500000,1022.666667,74.666667,NaN,0.170000,8.000000,...,6.146667,6.146667,0.000000,20.900000,7.100000,307.666667,17.600000,6.100000,8.553333,2024-03-01 00:00:00+09:00
1,1709222400,693.416667,97.750000,83.500000,2.508333,1022.500000,70.500000,NaN,0.000000,3.041667,...,6.255000,6.255000,0.000000,20.783333,5.091667,288.333333,26.366667,20.483333,6.256667,2024-03-01 01:00:00+09:00
2,1709226000,616.222222,86.333333,84.333333,2.433333,1022.833333,67.833333,NaN,0.210000,2.111111,...,5.926667,5.926667,0.000000,20.033333,4.733333,302.944444,27.433333,21.944444,7.291667,2024-03-01 02:00:00+09:00
3,1709229600,8692.363636,62.818182,83.666667,1.663636,1023.500000,63.833333,NaN,0.000000,0.900000,...,5.198333,5.198333,0.000000,19.900000,4.209091,277.666667,27.645455,22.490909,7.520000,2024-03-01 03:00:00+09:00
4,1709233200,10911.800000,38.100000,42.166667,-0.030000,1023.833333,64.833333,NaN,0.000000,-0.090000,...,4.433333,4.433333,0.000000,23.800000,3.180000,299.400000,42.440000,26.140000,7.330000,2024-03-01 04:00:00+09:00
5,1709236800,11582.400000,29.200000,50.000000,0.250000,1023.833333,67.500000,NaN,0.000000,-0.440000,...,3.640000,3.640000,0.000000,18.510000,2.930000,286.650000,30.660000,23.370000,7.356667,2024-03-01 05:00:00+09:00
6,1709240400,10252.363636,49.909091,71.166667,0.090909,1024.500000,64.500000,NaN,0.000000,-0.409091,...,3.356667,3.356667,0.000000,19.472727,2.690909,264.522727,28.427273,21.127273,8.348333,2024-03-01 06:00:00+09:00
7,1709244000,9434.909091,50.636364,73.428571,-1.627273,1024.571429,64.428571,NaN,0.000000,-1.572727,...,3.215714,3.215714,0.818182,23.100000,1.590909,262.727273,30.590909,23.945455,7.648571,2024-03-01 07:00:00+09:00
8,1709247600,10640.272727,44.454545,74.200000,-0.245455,1025.400000,66.200000,NaN,0.000000,-1.609091,...,2.074000,2.074000,1.000000,22.681818,2.227273,277.409091,34.063636,27.672727,8.702000,2024-03-01 08:00:00+09:00
9,1709251200,11288.636364,43.545455,75.000000,-1.418182,1025.500000,63.666667,NaN,0.000000,-0.390909,...,1.960000,1.960000,2.000000,22.245455,1.800000,268.439394,29.127273,24.445455,7.756667,2024-03-01 09:00:00+09:00
10,1709254800,9568.000000,55.833333,81.333333,-2.850000,1025.666667,61.000000,NaN,0.000000,0.241667,...,2.493333,2.493333,2.666667,23.183333,1.150000,278.041667,33.583333,25.258333,7.521667,2024-03-01 10:00:00+09:00
11,1709258400,8636.000000,30.833333,83.333333,-1.941667,1026.333333,62.166667,NaN,0.000000,-1.100000,...,1.990000,1.990000,3.916667,19.191667,1.375000,303.208333,35.358333,30.891667,7.775000,2024-03-01 11:00:00+09:00
12,1709262000,9144.000000,40.750000,80.500000,-2.691667,1027.000000,57.666667,NaN,0.000000,-0.283333,...,1.970000,1.970000,4.833333,18.383333,1.375000,298.000000,49.641667,30.558333,8.653333,2024-03-01 12:00:00+09:00
13,1709265600,8678.454545,77.000000,85.333333,-3.790909,1026.666667,58.666667,NaN,0.000000,-0.654545,...,2.100000,2.100000,3.272727,22.654545,0.972727,300.310606,45.909091,33.036364,8.835000,2024-03-01 13:00:00+09:00
14,1709269200,6581.461538,70.384615,85.833333,-2.584615,1025.333333,60.333333,NaN,0.000000,-0.961538,...,2.051667,2.051667,2.846154,17.830769,1.292308,298.910256,54.946154,29.361538,8.733333,2024-03-01 14:00:00+09:00
15,1709272800,7366.166667,77.416667,86.166667,-3.550000,1025.000000,60.500000,NaN,0.000000,-3.558333,...,1.973333,1.973333,2.166667,17.033333,0.500000,297.000000,54.575000,31.591667,9.625000,2024-03-01 15:00:00+09:00
16,1709276400,4937.833333,76.750000,87.500000,-4.883333,1024.500000,62.166667,NaN,0.000000,-3.966667,...,1.328333,1.328333,1.083333,21.833333,0.050000,295.291667,48.825000,31.725000,9.523333,2024-03-01 16:00:00+09:00
17,1709280000,6708.454545,76.090909,87.500000,-4.072727,1025.333333,56.166667,NaN,0.000000,-4.781818,...,1.206667,1.206667,0.909091,17.990909,0.027273,295.719697,62.527273,31.681818,9.903333,2024-03-01 17:00:00+09:00
18,1709283600,7153.700000,82.500000,85.714286,-4.100000,1025.428571,59.571429,NaN,0.000000,-6.010000,...,1.164286,1.164286,0.100000,18.510000,-0.360000,302.200000,52.590000,30.050000,9.682857,2024-03-01 18:00:00+09:00
19,1709287200,7838.909091,83.363636,90.000000,-4.690909,1025.600000,63.000000,NaN,0.038000,-5.127273,...,0.716000,0.716000,0.000000,23.390909,-0.718182,310.609091,40.627273,24.672727,9.260000,2024-03-01 19:00:00+09:00
20,1709290800,5142.818182,80.000000,87.500000,-3.890909,1026.500000,61.500000,NaN,0.021667,-5.290909,...,0.808333,0.808333,0.000000,21.809091,-0.572727,286.651515,45.154545,22.727273,8.301667,2024-03-01 20:00:00+09:00
21,1709294400,7977.454545,74.454545,87.500000,-4.727273,1026.500000,62.666667,NaN,0.000000,-4.627273,...,0.753333,0.753333,0.000000,23.863636,-0.554545,299.007576,44.745455,23.200000,7.956667,2024-03-01 21:00:00+09:00
22,1709298000,4918.363636,83.363636,85.714286,-5.654545,1026.428571,59.857143,NaN,0.000000,-4.527273,...,0.501429,0.501429,0.000000,24.854545,-1.236364,297.636364,34.400000,21.945455,7.444286,2024-03-01 22:00:00+09:00
23,1709301600,7110.272727,76.636364,87.500000,-5.800000,1027.000000,61.833333,NaN,0.000000,-4.381818,...,0.433333,0.433333,0.000000,23.127273,-1.363636,289.704545,23.518182,19.345455,6.946667,2024-03-01 23:00:00+09:00

In [26]:
columns_to_fill = [
   'precip_prob'
]

for col in columns_to_fill:
    for i in merged_df.index:
        if pd.isna(merged_df.loc[i, col]):  
            current_time = merged_df.loc[i, 'datetime']
            
            next_day_time = current_time + pd.Timedelta(days=1)
            
            next_day_data = merged_df[merged_df['datetime'] == next_day_time]
            
            if not next_day_data.empty:
                merged_df.loc[i, col] = next_day_data[col].values[0]

In [27]:
merged_df['hour'] = merged_df['datetime'].dt.hour
merged_df['month'] = merged_df['datetime'].dt.month
merged_df['day'] = merged_df['datetime'].dt.day

merged_df['hour_sin'] = np.sin(2 * np.pi * merged_df['hour'] / 24)

merged_df = merged_df.drop(columns=['hour'])

merged_df = merged_df.drop(columns=['datetime'])

In [28]:
merged_df = merged_df.copy()

merged_df['date'] = pd.to_datetime(merged_df['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')
merged_df['weekday'] = merged_df['date'].dt.dayofweek  

merged_df['월요일'] = (merged_df['weekday'] == 0).astype(int)  
merged_df['평일'] = merged_df['weekday'].isin(range(1, 5)).astype(int)  
merged_df['주말'] = merged_df['weekday'].isin([5, 6]).astype(int) 

merged_df['공휴일'] = 0

merged_df = merged_df.drop(columns=['date', 'weekday'])

In [29]:
holiday_dates = [
    '2024-03-01', '2024-05-05', '2024-05-15', '2024-06-06',
    '2024-08-15', '2024-09-16', '2024-09-17', '2024-09-18',
    '2024-10-03', '2024-10-09'
]

merged_df['date'] = pd.to_datetime(merged_df['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')
merged_df['공휴일'] = merged_df['date'].dt.strftime('%Y-%m-%d').isin(holiday_dates).astype(int)

merged_df = merged_df.drop(columns=['date'])

In [30]:
merged_df.rename(columns={
    '월요일': 'Monday',
    '평일': 'Weekday',
    '주말': 'Weekend',
    '공휴일': 'Holiday'
}, inplace=True)

In [31]:
merged_df = merged_df.drop(columns=['temp_max'])

In [32]:
merged_df

,ts,ceiling,cld_cvr,cloud,dew_point,ground_press,humidity,precip_prob,rain,real_feel_temp,...,wind_gust_spd,wind_spd,wind_speed,month,day,hour_sin,Monday,Weekday,Weekend,Holiday
0,1709218800,579.000000,91.000000,89.333333,5.500000,1022.666667,74.666667,0.000000,0.170000,8.000000,...,17.600000,6.100000,8.553333,3,1,0.000000,0,1,0,1
1,1709222400,693.416667,97.750000,83.500000,2.508333,1022.500000,70.500000,14.000000,0.000000,3.041667,...,26.366667,20.483333,6.256667,3,1,0.258819,0,1,0,1
2,1709226000,616.222222,86.333333,84.333333,2.433333,1022.833333,67.833333,14.888889,0.210000,2.111111,...,27.433333,21.944444,7.291667,3,1,0.500000,0,1,0,1
3,1709229600,8692.363636,62.818182,83.666667,1.663636,1023.500000,63.833333,14.444444,0.000000,0.900000,...,27.645455,22.490909,7.520000,3,1,0.707107,0,1,0,1
4,1709233200,10911.800000,38.100000,42.166667,-0.030000,1023.833333,64.833333,7.555556,0.000000,-0.090000,...,42.440000,26.140000,7.330000,3,1,0.866025,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6212,1731582000,8192.346667,54.888889,76.000000,15.246911,1019.000000,75.000000,13.444444,0.014111,17.530867,...,17.953144,12.159511,1.583333,11,14,-0.866025,0,1,0,0
6213,1731585600,6289.040000,57.000000,80.000000,15.493833,1019.666667,75.333333,14.888889,0.028222,17.839500,...,17.112711,12.374089,0.913333,11,14,-0.707107,0,1,0,0
6214,1731589200,3596.640000,68.333333,100.000000,15.617300,1019.333333,75.666667,17.888889,0.000000,18.024700,...,15.682189,13.393344,1.796667,11,14,-0.500000,0,1,0,0
6215,1731592800,579.120000,77.222222,100.000000,15.802489,1019.000000,76.000000,19.222222,0.000000,17.654322,...,16.111344,14.412600,1.303333,11,14,-0.258819,0,1,0,0
6216,1731596400,579.120000,89.333333,100.000000,15.925944,1018.666667,77.000000,21.111111,0.070556,17.716044,...,16.486856,15.038456,2.400000,11,15,0.000000,0,1,0,0

In [33]:
merged_df = merged_df.drop(columns=['precip_prob'])

# ***예측날 테이블 만들기***

In [34]:
date = '2024-11-14'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzMxMjAxMzE4LCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.1HewB2-rCsqpwLN4FlbwPOAOoIDK54phUZmcJorS2W4"

weather_forecast = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/weather-forecast/{date}', headers={
    'Authorization': f'Bearer {token}'
}).json()

df_weather_forecast_1 = pd.DataFrame(weather_forecast['weather_forecast_1'])
df_weather_forecast_2 = pd.DataFrame(weather_forecast['weather_forecast_2'])

df_weather_forecast_1 = df_weather_forecast_1.drop(columns=['location', 'base_ts'], errors='ignore')
df_weather_forecast_2 = df_weather_forecast_2.drop(columns=['location', 'base_ts'], errors='ignore')

In [35]:
df_weather_forecast_2

,ts,cloud,temp,temp_max,temp_min,humidity,ground_press,wind_speed,wind_dir,rain,snow
0,1731596400,100.0,19.46,19.46,19.46,83.0,1018.0,1.80,179.0,0.77,0.0
1,1731600000,100.0,19.39,19.39,19.39,84.0,1017.0,1.35,142.0,0.40,0.0
2,1731603600,100.0,19.24,19.24,19.24,85.0,1017.0,1.21,111.0,0.45,0.0
3,1731607200,100.0,19.19,19.19,19.19,84.0,1017.0,1.47,106.0,0.23,0.0
4,1731610800,100.0,19.10,19.10,19.10,84.0,1017.0,1.84,110.0,0.32,0.0
...,...,...,...,...,...,...,...,...,...,...,...
70,1731668400,100.0,20.14,20.14,20.14,94.0,1017.0,5.33,102.0,0.21,0.0
71,1731672000,100.0,20.24,20.24,20.24,94.0,1017.0,4.77,96.0,0.00,0.0
72,1731675600,100.0,20.00,20.00,20.00,94.0,1017.0,4.43,93.0,0.78,0.0
73,1731679200,100.0,19.79,19.79,19.79,95.0,1017.0,4.63,82.0,0.62,0.0
74,1731682800,100.0,19.68,19.68,19.68,95.0,1017.0,5.21,89.0,0.21,0.0

In [36]:
start_ts = 1731600000 # 11/14일 01:00시

timestamps = [start_ts + i * 3600 for i in range(24)]

new_data = {
    'ts': timestamps
}
new_df = pd.DataFrame(new_data)

In [37]:
df_weather_forecast_1_grouped = df_weather_forecast_1.groupby('ts').mean().reset_index()
df_weather_forecast_2_grouped = df_weather_forecast_2.groupby('ts').mean().reset_index()

new_df = pd.merge(new_df, df_weather_forecast_1_grouped, on='ts', how='left', suffixes=('', '_1'))
new_df = pd.merge(new_df, df_weather_forecast_2_grouped, on='ts', how='left', suffixes=('', '_2'))

for column in new_df.columns:
    if '_1' in column or '_2' in column:
        base_column = column.replace('_1', '').replace('_2', '')
        if base_column in new_df.columns:
            new_df[base_column] = new_df[[base_column, column]].mean(axis=1)

new_df = new_df.loc[:, ~new_df.columns.str.endswith(('_1', '_2'))]

In [38]:
columns_to_drop = ['ice', 'snow_prob', 'ice_prob', 'snow', 'rain_prob', 'total_liq']

new_df = new_df.drop(columns=columns_to_drop)

In [39]:
new_df['datetime'] = pd.to_datetime(new_df['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')

In [40]:
new_df['hour'] = new_df['datetime'].dt.hour
new_df['month'] = new_df['datetime'].dt.month
new_df['day'] = new_df['datetime'].dt.day

new_df['hour_sin'] = np.sin(2 * np.pi * new_df['hour'] / 24)

new_df = new_df.drop(columns=['hour'])

new_df = new_df.drop(columns=['datetime'])

In [41]:
new_df = new_df.copy()

new_df['date'] = pd.to_datetime(new_df['ts'], unit='s', utc=True).dt.tz_convert('Asia/Seoul')
new_df['weekday'] = new_df['date'].dt.dayofweek  

new_df['월요일'] = (new_df['weekday'] == 0).astype(int)  
new_df['평일'] = new_df['weekday'].isin(range(1, 5)).astype(int)  
new_df['주말'] = new_df['weekday'].isin([5, 6]).astype(int) 

new_df['공휴일'] = 0

new_df = new_df.drop(columns=['date', 'weekday'])

In [42]:
new_df.rename(columns={
    '월요일': 'Monday',
    '평일': 'Weekday',
    '주말': 'Weekend',
    '공휴일': 'Holiday'
}, inplace=True)

In [43]:
new_df = new_df.drop(columns=['temp_max'])

In [44]:
new_df

,ts,temp,real_feel_temp,wet_bulb_temp,dew_point,wind_spd,wind_dir,wind_gust_spd,rel_hum,vis,...,humidity,ground_press,wind_speed,month,day,hour_sin,Monday,Weekday,Weekend,Holiday
0,1731600000,18.588894,17.654322,16.975311,15.308644,15.449733,154.111111,17.112711,76.666667,8.046720,...,84.666667,1017.666667,0.686667,11,15,2.588190e-01,0,1,0,0
1,1731603600,18.476289,17.222233,17.098778,15.493822,16.272289,131.888889,17.523978,79.333333,8.046720,...,84.666667,1017.333333,0.856667,11,15,5.000000e-01,0,1,0,0
2,1731607200,18.435428,17.530867,17.160500,15.802456,15.843133,152.777778,17.756456,80.888889,8.046720,...,83.666667,1017.000000,0.846667,11,15,7.071068e-01,0,1,0,0
3,1731610800,18.361239,17.592600,17.283944,15.987656,15.431856,157.666667,17.524000,81.666667,8.046720,...,85.000000,1017.000000,1.436667,11,15,8.660254e-01,0,1,0,0
4,1731614400,18.469622,17.654333,17.407389,16.111111,14.233778,151.944444,17.702822,82.333333,8.046720,...,84.666667,1017.000000,1.920000,11,15,9.659258e-01,0,1,0,0
5,1731618000,18.499689,17.777789,17.716056,16.419778,13.607922,151.722222,19.365767,83.111111,8.046720,...,87.666667,1017.000000,1.733333,11,15,1.000000e+00,0,1,0,0
6,1731621600,18.527156,18.333311,17.839522,16.666678,12.767489,138.333333,20.599633,84.777778,7.689089,...,88.666667,1017.000000,3.096667,11,15,9.659258e-01,0,1,0,0
7,1731625200,18.392956,18.580233,18.086422,17.037056,11.354831,131.944444,20.385044,87.666667,7.152642,...,92.666667,1017.000000,3.273333,11,15,8.660254e-01,0,1,0,0
8,1731628800,18.456350,19.320978,18.333344,17.592578,10.317696,124.666667,19.973767,89.222222,6.795011,...,94.666667,1018.000000,3.500000,11,15,7.071068e-01,0,1,0,0
9,1731632400,18.769083,19.753100,18.641956,17.716033,10.514396,127.722222,21.010911,88.555556,7.331458,...,94.666667,1017.666667,4.213333,11,15,5.000000e-01,0,1,0,0
10,1731636000,19.095867,19.938289,18.765422,17.962978,9.906418,134.055556,21.618878,87.444444,7.152642,...,93.333333,1017.000000,4.106667,11,15,2.588190e-01,0,1,0,0
11,1731639600,19.214261,20.308644,19.074078,18.086433,10.317698,139.222222,22.441422,87.333333,7.152642,...,94.000000,1017.000000,4.223333,11,15,1.224647e-16,0,1,0,0
12,1731643200,19.373522,20.432089,19.074078,18.148156,11.336956,140.611111,25.141544,87.111111,6.616196,...,94.333333,1016.000000,3.860000,11,15,-2.588190e-01,0,1,0,0
13,1731646800,19.393589,19.814844,19.135800,18.148156,13.017822,128.277778,26.983322,86.777778,6.437380,...,95.666667,1015.666667,3.593333,11,15,-5.000000e-01,0,1,0,0
14,1731650400,19.668706,20.000011,19.197522,18.271600,13.214522,131.722222,28.413833,85.333333,6.437380,...,93.333333,1016.000000,3.476667,11,15,-7.071068e-01,0,1,0,0
15,1731654000,19.552789,19.938267,19.197522,18.333333,12.588667,133.166667,27.591289,86.666667,6.437380,...,94.333333,1016.000000,3.580000,11,15,-8.660254e-01,0,1,0,0
16,1731657600,19.448528,19.691356,19.259244,18.333333,11.748233,139.222222,27.180022,87.666667,6.437380,...,94.333333,1016.000000,4.416667,11,15,-9.659258e-01,0,1,0,0
17,1731661200,19.493522,19.876544,19.320967,18.333333,11.336956,150.111111,25.946211,87.666667,6.437380,...,94.333333,1016.333333,4.856667,11,15,-1.000000e+00,0,1,0,0
18,1731664800,19.623578,19.814811,19.259233,18.333333,11.158133,142.944444,25.964089,86.222222,6.437380,...,93.666667,1016.666667,5.376667,11,15,-9.659258e-01,0,1,0,0
19,1731668400,19.531739,19.135800,19.012333,18.209878,11.390589,127.666667,26.554167,87.666667,6.437380,...,92.666667,1016.666667,5.126667,11,15,-8.660254e-01,0,1,0,0
20,1731672000,19.515011,18.827156,18.827144,18.024689,11.372709,77.500000,26.572044,88.222222,6.437380,...,92.666667,1017.000000,4.466667,11,15,-7.071068e-01,0,1,0,0
21,1731675600,19.348278,19.074056,18.827144,17.962956,11.783989,83.111111,26.589922,88.111111,6.616196,...,93.000000,1017.000000,4.103333,11,15,-5.000000e-01,0,1,0,0
22,1731679200,19.322478,19.320989,18.765422,17.839489,11.569409,81.944444,26.375356,87.333333,7.152642,...,93.333333,1017.000000,4.496667,11,15,-2.588190e-01,0,1,0,0
23,1731682800,19.252478,19.320978,18.703700,17.839489,11.569409,86.611111,26.786622,87.222222,7.510273,...,93.666667,1017.000000,5.186667,11,16,0.000000e+00,0,0,1,0

In [45]:
new_df = new_df.drop(columns=['precip_prob'])

# ***대회 평가지표***

In [46]:
def calculate_measure(actual, forecast):
    actual = np.array(actual)
    forecast = np.array(forecast)

    positive_index = actual > 0
    negative_index = actual <= 0

    # actual은 0과 -1 사이의 값을 처리
    actual[(actual <= 0) & (actual > -1)] = -1
    
    # 긍정적 및 부정적 가격의 수
    n1 = np.sum(positive_index) + 1e-7
    n2 = np.sum(negative_index) + 1e-7

    # e1: 긍정적 가격 예측 오차 비율
    e1 = (
        np.sum(
            np.abs(actual[positive_index] - forecast[positive_index])
            / np.abs(actual[positive_index])
        )
        / n1
    )

    # e2: 부정적 가격 예측 오차 비율
    e2 = (
        np.sum(
            np.abs(actual[negative_index] - forecast[negative_index])
            / np.abs(actual[negative_index])
        )
        / n2
    )

    TP = np.sum((forecast > 0) & (actual > 0))
    TN = np.sum((forecast <= 0) & (actual <= 0))
    FP = np.sum((forecast > 0) & (actual <= 0))
    FN = np.sum((forecast <= 0) & (actual > 0))

    # 정확도 계산
    Accuracy = (TP + TN) / (TP + TN + FP + FN)
    print(f'Accuracy: {Accuracy}')
    print(f'e1: {e1}, e2: {e2}')

    e_F = 0.2 * e1 + 0.8 * e2 - (Accuracy - 0.95)

    return e_F

# ***예측 모델 돌리기***

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler

# 특성 및 목표 변수 정의
target = 'smp_da'
features = merged_df.columns.difference([target])

# 훈련 데이터와 검증 데이터 분리
train_data = merged_df.iloc[:-72]
valid_data = merged_df.iloc[-72:]

# 특성과 타겟 변수 분리
X_train = train_data[features]
y_train = train_data[target]
X_valid = valid_data[features]
y_valid = valid_data[target]

# MinMax 스케일링 적용
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_new_scaled = scaler.transform(new_df[features])  # new_df에 스케일 적용

# RandomForest 모델 훈련
rf_model = RandomForestRegressor(n_estimators=250, random_state=42)
rf_model.fit(X_train_scaled, y_train)

# RandomForest 예측
y_train_pred_rf = rf_model.predict(X_train_scaled)
y_valid_pred_rf = rf_model.predict(X_valid_scaled)
y_new_pred_rf = rf_model.predict(X_new_scaled)

# RandomForest 예측 값과 실제 값의 잔차 계산
residual_train = y_train - y_train_pred_rf

# SVR 모델을 잔차 보정 모델로 훈련 (RandomForest 예측 값을 입력으로 사용)
svr_model_corrector = SVR(kernel='rbf', C=50, epsilon=2)
svr_model_corrector.fit(y_train_pred_rf.reshape(-1, 1), residual_train)

# SVR 모델로 잔차 보정 예측
residual_valid_pred_svr = svr_model_corrector.predict(y_valid_pred_rf.reshape(-1, 1))
residual_new_pred_svr = svr_model_corrector.predict(y_new_pred_rf.reshape(-1, 1))

# 최종 예측 (RandomForest 예측 + SVR로 예측한 잔차 보정)
y_valid_final_pred = y_valid_pred_rf + residual_valid_pred_svr
y_new_final_pred = y_new_pred_rf + residual_new_pred_svr

# 검증 데이터 평가
measure = calculate_measure(y_valid, y_valid_final_pred)
print("Custom Measure for Validation (Residual Corrector Ensemble):", measure)

# 최종 예측 출력
print("Predicted SMP for 2024-11-12 (24 hours, Residual Corrector Ensemble):", y_new_final_pred)

In [47]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler

# 특성 및 목표 변수 정의
target = 'smp_da'
features = merged_df.columns.difference([target])

# 훈련 데이터와 검증 데이터 분리
train_data = merged_df.iloc[:-72]
valid_data = merged_df.iloc[-72:]

# 특성과 타겟 변수 분리
X_train = train_data[features]
y_train = train_data[target]
X_valid = valid_data[features]
y_valid = valid_data[target]

# MinMax 스케일링 적용
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_new_scaled = scaler.transform(new_df[features])  # new_df에 스케일 적용

# RandomForest 모델 훈련
rf_model = RandomForestRegressor(n_estimators=250, random_state=42)
rf_model.fit(X_train_scaled, y_train)

# RandomForest 예측
y_train_pred_rf = rf_model.predict(X_train_scaled)
y_valid_pred_rf = rf_model.predict(X_valid_scaled)
y_new_pred_rf = rf_model.predict(X_new_scaled)

# RandomForest 예측 값과 실제 값의 잔차 계산
residual_train = y_train - y_train_pred_rf

# SVR 모델을 잔차 보정 모델로 훈련 (RandomForest 예측 값을 입력으로 사용)
svr_model_corrector = SVR(kernel='rbf', C=50, epsilon=2)
svr_model_corrector.fit(y_train_pred_rf.reshape(-1, 1), residual_train)

# SVR 모델로 잔차 보정 예측
residual_valid_pred_svr = svr_model_corrector.predict(y_valid_pred_rf.reshape(-1, 1))
residual_new_pred_svr = svr_model_corrector.predict(y_new_pred_rf.reshape(-1, 1))

# 최종 예측 (RandomForest 예측 + SVR로 예측한 잔차 보정)
y_valid_final_pred = y_valid_pred_rf + residual_valid_pred_svr
y_new_final_pred = y_new_pred_rf + residual_new_pred_svr

# 검증 데이터 평가
measure = calculate_measure(y_valid, y_valid_final_pred)
print("Custom Measure for Validation (Residual Corrector Ensemble):", measure)

# 최종 예측 출력
print("Predicted SMP for 2024-11-12 (24 hours, Residual Corrector Ensemble):", y_new_final_pred)

Accuracy: 1.0
e1: 0.06553602147369751, e2: 0.0
Custom Measure for Validation (Residual Corrector Ensemble): -0.036892795705260543
Predicted SMP for 2024-11-12 (24 hours, Residual Corrector Ensemble): [114.39707978 109.4455531  105.48777013 112.1511659  110.81780878
 109.50352565 110.06660269 108.31190527 124.17511659 143.58784902
 140.69082609 128.97910401 123.05731483 121.42117144 125.31290264
 125.24065509 128.37585543 128.66665427 128.53818272 125.29519917
 125.11627692 117.6968574  113.86155687 125.29038292]

In [48]:
import optuna

# Define the objective function for Optuna with your custom metric
def objective(trial):
    # Suggest hyperparameters for RandomForest
    rf_n_estimators = trial.suggest_int("rf_n_estimators", 100, 500)
    rf_max_depth = trial.suggest_int("rf_max_depth", 5, 30)
    rf_min_samples_split = trial.suggest_int("rf_min_samples_split", 2, 10)
    rf_min_samples_leaf = trial.suggest_int("rf_min_samples_leaf", 1, 4)
    
    # Suggest hyperparameters for SVR with suggest_float instead of suggest_loguniform
    svr_C = trial.suggest_float("svr_C", 1e-1, 1e2, log=True)
    svr_epsilon = trial.suggest_float("svr_epsilon", 1e-2, 1e1, log=True)
    
    # Train RandomForest with suggested hyperparameters
    rf_model = RandomForestRegressor(
        n_estimators=rf_n_estimators,
        max_depth=rf_max_depth,
        min_samples_split=rf_min_samples_split,
        min_samples_leaf=rf_min_samples_leaf,
        random_state=42
    )
    rf_model.fit(X_train_scaled, y_train)

    # Predict with RandomForest
    y_train_pred_rf = rf_model.predict(X_train_scaled)
    y_valid_pred_rf = rf_model.predict(X_valid_scaled)

    # Calculate residuals for training data
    residual_train = y_train - y_train_pred_rf

    # Train SVR on residuals with suggested hyperparameters
    svr_model_corrector = SVR(kernel='rbf', C=svr_C, epsilon=svr_epsilon)
    svr_model_corrector.fit(y_train_pred_rf.reshape(-1, 1), residual_train)

    # Predict residuals for validation data
    residual_valid_pred_svr = svr_model_corrector.predict(y_valid_pred_rf.reshape(-1, 1))

    # Final predictions for validation data
    y_valid_final_pred = y_valid_pred_rf + residual_valid_pred_svr

    # Calculate the custom measure on validation data
    custom_error = calculate_measure(y_valid, y_valid_final_pred)
    return custom_error

# Set up Optuna study and run optimization
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50)

# Get best hyperparameters
best_params = study.best_params
print("Best Hyperparameters:", best_params)

# Train models with best hyperparameters on the full dataset
rf_model = RandomForestRegressor(
    n_estimators=best_params["rf_n_estimators"],
    max_depth=best_params["rf_max_depth"],
    min_samples_split=best_params["rf_min_samples_split"],
    min_samples_leaf=best_params["rf_min_samples_leaf"],
    random_state=42
)
rf_model.fit(X_train_scaled, y_train)

# RandomForest predictions
y_train_pred_rf = rf_model.predict(X_train_scaled)
y_valid_pred_rf = rf_model.predict(X_valid_scaled)
y_new_pred_rf = rf_model.predict(X_new_scaled)

# SVR residual corrector with best hyperparameters
svr_model_corrector = SVR(kernel='rbf', C=best_params["svr_C"], epsilon=best_params["svr_epsilon"])
svr_model_corrector.fit(y_train_pred_rf.reshape(-1, 1), residual_train)

# Correct residuals
residual_valid_pred_svr = svr_model_corrector.predict(y_valid_pred_rf.reshape(-1, 1))
residual_new_pred_svr = svr_model_corrector.predict(y_new_pred_rf.reshape(-1, 1))

# Final predictions with residual correction
y_valid_final_pred = y_valid_pred_rf + residual_valid_pred_svr
y_new_final_pred = y_new_pred_rf + residual_new_pred_svr

# Calculate final measure and display results
measure = calculate_measure(y_valid, y_valid_final_pred)
print("Custom Measure for Validation (Residual Corrector Ensemble):", measure)
print("Predicted SMP for 2024-11-12 (24 hours, Residual Corrector Ensemble):", y_new_final_pred)

[I 2024-11-14 10:43:54,985] A new study created in memory with name: no-name-b5f8d074-f929-4979-96b0-828e5bad619f
[I 2024-11-14 10:44:08,194] Trial 0 finished with value: -0.0269326608849218 and parameters: {'rf_n_estimators': 166, 'rf_max_depth': 7, 'rf_min_samples_split': 3, 'rf_min_samples_leaf': 2, 'svr_C': 7.168006832957056, 'svr_epsilon': 0.012813823659560096}. Best is trial 0 with value: -0.0269326608849218.

Accuracy: 1.0
e1: 0.11533669557539121, e2: 0.0

[I 2024-11-14 10:44:18,410] Trial 1 finished with value: -0.02458147609559781 and parameters: {'rf_n_estimators': 146, 'rf_max_depth': 6, 'rf_min_samples_split': 3, 'rf_min_samples_leaf': 3, 'svr_C': 45.08686257781691, 'svr_epsilon': 1.9490122623081017}. Best is trial 0 with value: -0.0269326608849218.

Accuracy: 1.0
e1: 0.12709261952201117, e2: 0.0

[I 2024-11-14 10:45:13,960] Trial 2 finished with value: -0.03673884010279745 and parameters: {'rf_n_estimators': 459, 'rf_max_depth': 29, 'rf_min_samples_split': 5, 'rf_min_samples_leaf': 4, 'svr_C': 0.503783703613242, 'svr_epsilon': 0.8260894688897515}. Best is trial 2 with value: -0.03673884010279745.

Accuracy: 1.0
e1: 0.06630579948601295, e2: 0.0

[I 2024-11-14 10:46:08,970] Trial 3 finished with value: -0.03639337307053891 and parameters: {'rf_n_estimators': 385, 'rf_max_depth': 26, 'rf_min_samples_split': 7, 'rf_min_samples_leaf': 1, 'svr_C': 0.5891309007459364, 'svr_epsilon': 0.19712382410930487}. Best is trial 2 with value: -0.03673884010279745.

Accuracy: 1.0
e1: 0.06803313464730569, e2: 0.0

[I 2024-11-14 10:47:11,792] Trial 4 finished with value: -0.036656451081813236 and parameters: {'rf_n_estimators': 475, 'rf_max_depth': 30, 'rf_min_samples_split': 7, 'rf_min_samples_leaf': 2, 'svr_C': 0.10052442632906015, 'svr_epsilon': 0.44589497203127654}. Best is trial 2 with value: -0.03673884010279745.

Accuracy: 1.0
e1: 0.06671774459093405, e2: 0.0

[I 2024-11-14 10:47:58,007] Trial 5 finished with value: -0.0369658716010952 and parameters: {'rf_n_estimators': 364, 'rf_max_depth': 22, 'rf_min_samples_split': 10, 'rf_min_samples_leaf': 3, 'svr_C': 0.38535349523702067, 'svr_epsilon': 0.04737726488913967}. Best is trial 5 with value: -0.0369658716010952.

Accuracy: 1.0
e1: 0.06517064199452424, e2: 0.0

[I 2024-11-14 10:48:29,741] Trial 6 finished with value: -0.0368022090884767 and parameters: {'rf_n_estimators': 268, 'rf_max_depth': 28, 'rf_min_samples_split': 3, 'rf_min_samples_leaf': 4, 'svr_C': 0.878791392377062, 'svr_epsilon': 0.5632373418261895}. Best is trial 5 with value: -0.0369658716010952.

Accuracy: 1.0
e1: 0.0659889545576167, e2: 0.0

[I 2024-11-14 10:49:20,595] Trial 7 finished with value: -0.03685498192726623 and parameters: {'rf_n_estimators': 383, 'rf_max_depth': 23, 'rf_min_samples_split': 9, 'rf_min_samples_leaf': 2, 'svr_C': 3.2941018549116694, 'svr_epsilon': 0.08216710813088106}. Best is trial 5 with value: -0.0369658716010952.

Accuracy: 1.0
e1: 0.06572509036366907, e2: 0.0

[I 2024-11-14 10:49:59,316] Trial 8 finished with value: -0.03698936478978839 and parameters: {'rf_n_estimators': 365, 'rf_max_depth': 12, 'rf_min_samples_split': 7, 'rf_min_samples_leaf': 2, 'svr_C': 0.9021280933758006, 'svr_epsilon': 0.21468499334052582}. Best is trial 8 with value: -0.03698936478978839.

Accuracy: 1.0
e1: 0.06505317605105826, e2: 0.0

[I 2024-11-14 10:51:00,803] Trial 9 finished with value: -0.0364018781418281 and parameters: {'rf_n_estimators': 479, 'rf_max_depth': 18, 'rf_min_samples_split': 10, 'rf_min_samples_leaf': 1, 'svr_C': 17.64452918091289, 'svr_epsilon': 0.06910195911434326}. Best is trial 8 with value: -0.03698936478978839.

Accuracy: 1.0
e1: 0.06799060929085972, e2: 0.0

[I 2024-11-14 10:51:25,784] Trial 10 finished with value: -0.036090443602170494 and parameters: {'rf_n_estimators': 252, 'rf_max_depth': 11, 'rf_min_samples_split': 5, 'rf_min_samples_leaf': 1, 'svr_C': 92.36145712866286, 'svr_epsilon': 4.394897956644672}. Best is trial 8 with value: -0.03698936478978839.

Accuracy: 1.0
e1: 0.06954778198914775, e2: 0.0

[I 2024-11-14 10:52:07,315] Trial 11 finished with value: -0.036985934821852494 and parameters: {'rf_n_estimators': 350, 'rf_max_depth': 16, 'rf_min_samples_split': 9, 'rf_min_samples_leaf': 3, 'svr_C': 0.14002599468386126, 'svr_epsilon': 0.01329514461074976}. Best is trial 8 with value: -0.03698936478978839.

Accuracy: 1.0
e1: 0.06507032589073775, e2: 0.0

[I 2024-11-14 10:52:44,285] Trial 12 finished with value: -0.036915140628723586 and parameters: {'rf_n_estimators': 319, 'rf_max_depth': 14, 'rf_min_samples_split': 8, 'rf_min_samples_leaf': 3, 'svr_C': 0.11863445410839113, 'svr_epsilon': 0.018214947783990597}. Best is trial 8 with value: -0.03698936478978839.

Accuracy: 1.0
e1: 0.0654242968563823, e2: 0.0

[I 2024-11-14 10:53:22,621] Trial 13 finished with value: -0.03715401259479464 and parameters: {'rf_n_estimators': 321, 'rf_max_depth': 16, 'rf_min_samples_split': 8, 'rf_min_samples_leaf': 3, 'svr_C': 1.7931002862131178, 'svr_epsilon': 8.935189798260327}. Best is trial 13 with value: -0.03715401259479464.

Accuracy: 1.0
e1: 0.06422993702602704, e2: 0.0

[I 2024-11-14 10:53:42,977] Trial 14 finished with value: -0.03614878019363414 and parameters: {'rf_n_estimators': 215, 'rf_max_depth': 10, 'rf_min_samples_split': 6, 'rf_min_samples_leaf': 2, 'svr_C': 1.9371420839854483, 'svr_epsilon': 4.958472985447618}. Best is trial 13 with value: -0.03715401259479464.

Accuracy: 1.0
e1: 0.06925609903182951, e2: 0.0

[I 2024-11-14 10:54:33,513] Trial 15 finished with value: -0.036753365184582235 and parameters: {'rf_n_estimators': 421, 'rf_max_depth': 20, 'rf_min_samples_split': 7, 'rf_min_samples_leaf': 4, 'svr_C': 2.845823207311836, 'svr_epsilon': 0.19791289559474293}. Best is trial 13 with value: -0.03715401259479464.

Accuracy: 1.0
e1: 0.06623317407708905, e2: 0.0

[W 2024-11-14 10:54:42,188] Trial 16 failed with parameters: {'rf_n_estimators': 295, 'rf_max_depth': 13, 'rf_min_samples_split': 5, 'rf_min_samples_leaf': 3, 'svr_C': 1.370204134548706, 'svr_epsilon': 9.946172690646545} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda\Lib\site-packages\optuna\study\_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\언종\AppData\Local\Temp\ipykernel_460\2540707345.py", line 23, in objective
    rf_model.fit(X_train_scaled, y_train)
  File "C:\Users\Administrator\anaconda\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda\Lib\site-packages\sklearn\ensemble\_forest.py", line 489, in fit
    trees = Parallel(
            ^^^^^^^^^
  File "C:\Users\Administrator\anaconda\Lib\site-packages\sklearn\utils\parallel.py", line 67, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda\Lib\site-packages\joblib\parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda\Lib\site-packages\joblib\parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda\Lib\site-packages\sklearn\utils\parallel.py", line 129, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda\Lib\site-packages\sklearn\ensemble\_forest.py", line 192, in _parallel_build_trees
    tree._fit(
  File "C:\Users\Administrator\anaconda\Lib\site-packages\sklearn\tree\_classes.py", line 472, in _fit
    builder.build(self.tree_, X, y, sample_weight, missing_values_in_feature_mask)
KeyboardInterrupt
[W 2024-11-14 10:54:42,197] Trial 16 failed with value None.

KeyboardInterrupt:

In [49]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler

# 특성 및 목표 변수 정의
target = 'smp_da'
features = merged_df.columns.difference([target])

# 훈련 데이터와 검증 데이터 분리
train_data = merged_df.iloc[:-72]
valid_data = merged_df.iloc[-72:]

# 특성과 타겟 변수 분리
X_train = train_data[features]
y_train = train_data[target]
X_valid = valid_data[features]
y_valid = valid_data[target]

# MinMax 스케일링 적용
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_valid_scaled = scaler.transform(X_valid)
X_new_scaled = scaler.transform(new_df[features])  # new_df에 스케일 적용

# RandomForest 모델 훈련
rf_model = RandomForestRegressor(
    n_estimators=321,
    max_depth=16,
    min_samples_split=8,
    min_samples_leaf=3,
    random_state=42
)
rf_model.fit(X_train_scaled, y_train)

# RandomForest 예측
y_train_pred_rf = rf_model.predict(X_train_scaled)
y_valid_pred_rf = rf_model.predict(X_valid_scaled)
y_new_pred_rf = rf_model.predict(X_new_scaled)

# RandomForest 예측 값과 실제 값의 잔차 계산
residual_train = y_train - y_train_pred_rf

# SVR 모델을 잔차 보정 모델로 훈련 (RandomForest 예측 값을 입력으로 사용)
svr_model_corrector = SVR(
    kernel='rbf',
    C=1.7931002862131178,
    epsilon=8.935189798260327
)
svr_model_corrector.fit(y_train_pred_rf.reshape(-1, 1), residual_train)

# SVR 모델로 잔차 보정 예측
residual_valid_pred_svr = svr_model_corrector.predict(y_valid_pred_rf.reshape(-1, 1))
residual_new_pred_svr = svr_model_corrector.predict(y_new_pred_rf.reshape(-1, 1))

# 최종 예측 (RandomForest 예측 + SVR로 예측한 잔차 보정)
y_valid_final_pred = y_valid_pred_rf + residual_valid_pred_svr
y_new_final_pred = y_new_pred_rf + residual_new_pred_svr

# 검증 데이터 평가
measure = calculate_measure(y_valid, y_valid_final_pred)
print("Custom Measure for Validation (Residual Corrector Ensemble):", measure)

# 최종 예측 출력
print("Predicted SMP for 2024-11-12 (24 hours, Residual Corrector Ensemble):", y_new_final_pred)

Accuracy: 1.0
e1: 0.06422993702602704, e2: 0.0
Custom Measure for Validation (Residual Corrector Ensemble): -0.03715401259479464
Predicted SMP for 2024-11-12 (24 hours, Residual Corrector Ensemble): [115.11089336 107.07712637 105.00494227 110.53690904 109.15065459
 109.04189984 108.98164425 108.9046646  120.34101628 144.26399487
 140.28708504 128.93506408 124.8957062  122.15823791 127.00826081
 127.29915065 130.3769316  130.64189321 130.59741503 127.22344126
 125.41741186 118.62048504 115.58430368 123.85070501]

# ***제출***

In [50]:
import json
import requests

result = {
    'submit_result': y_new_final_pred.tolist()  
}

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzMxMjAxMzE4LCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.1HewB2-rCsqpwLN4FlbwPOAOoIDK54phUZmcJorS2W4"

try:
    response = requests.post(
        'https://research-api.solarkim.com/submissions/cmpt-2024',
        data=json.dumps(result),
        headers={
            'Authorization': f'Bearer {token}',
            'Content-Type': 'application/json'
        }
    )
    success = response.json()
    print("Submission response:", success)
except requests.exceptions.RequestException as e:
    print("Submission failed:", e)

Submission response: True

# ***예측날 값 불러오기***

In [ ]:
import requests

date = '2024-11-13'
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqaUtiN01nazVKZThnd3JTbmFmMk1HIiwiaWF0IjoxNzMxMjAxMzE4LCJleHAiOjE3MzE1OTY0MDAsInR5cGUiOiJhcGlfa2V5In0.1HewB2-rCsqpwLN4FlbwPOAOoIDK54phUZmcJorS2W4"

smp_da = requests.get(f'https://research-api.solarkim.com/data/cmpt-2024/smp-da/{date}', headers={
                            'Authorization': f'Bearer {token}'
                        }).json()
smp_da = pd.DataFrame(smp_da)
smp_da

# ***그래프 비교***

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import timezone, timedelta

# 새로운 data1 값 설정 (여기에 기존의 `data1`을 수정한 내용 반영)
data1 = {
    'ts': [
        1731340800, 1731344400, 1731348000, 1731351600, 1731355200, 1731358800,
        1731362400, 1731366000, 1731369600, 1731373200, 1731376800, 1731380400,
        1731384000, 1731387600, 1731391200, 1731394800, 1731398400, 1731402000,
        1731405600, 1731409200, 1731412800, 1731416400, 1731420000, 1731423600
    ],
    'smp_da': [
      103.76, 87.57, 83.40, 85.30, 87.57, 102.76, 116.73, 116.73, 147.26,
        147.26, 147.26, 132.31, 132.31, 132.31, 147.26, 147.26, 147.26, 139.97,
        132.32, 116.98, 126.24, 125.50, 106.52, 105.55

    ]
}
df1 = pd.DataFrame(data1)

# 기존 data2 값 설정
data2 = {
    'ts': df1['ts'],  # data1의 ts 값을 그대로 사용
    'smp_da': [
 112.131, 92.21, 88.973, 90.822, 92.624, 88.468, 91.044, 107.99, 137.418, 130.909, 121.041,
        117.798, 109.092, 111.078, 126.305, 127.934, 126.719, 131.4, 131.058, 126.116, 123.307,
        114.455, 110.105, 111.338


    ]
}
df2 = pd.DataFrame(data2)

# ts를 KST로 변환
kst = timezone(timedelta(hours=9))
df1['ts'] = pd.to_datetime(df1['ts'], unit='s', utc=True).dt.tz_convert(kst)
df2['ts'] = pd.to_datetime(df2['ts'], unit='s', utc=True).dt.tz_convert(kst)

# 그래프 그리기
plt.figure(figsize=(12, 6))
plt.plot(df1['ts'], df1['smp_da'], label='Updated DataFrame 1 (df1)', marker='o')
plt.plot(df2['ts'], df2['smp_da'], label='Updated DataFrame 2 (df2)', marker='o')

plt.xticks(rotation=45)
plt.xlabel('Timestamp (KST)')
plt.ylabel('smp_da Value')
plt.title('Comparison of smp_da between updated df1 and df2 with new data')
plt.legend()
plt.grid()
plt.tight_layout()
plt.show()

# ***e_F 계산***

In [ ]:
data1 = {
    'ts': [
        1731340800, 1731344400, 1731348000, 1731351600, 1731355200, 1731358800,
        1731362400, 1731366000, 1731369600, 1731373200, 1731376800, 1731380400,
        1731384000, 1731387600, 1731391200, 1731394800, 1731398400, 1731402000,
        1731405600, 1731409200, 1731412800, 1731416400, 1731420000, 1731423600
    ],
    'smp_da': [
      103.76, 87.57, 83.40, 85.30, 87.57, 102.76, 116.73, 116.73, 147.26,
        147.26, 147.26, 132.31, 132.31, 132.31, 147.26, 147.26, 147.26, 139.97,
        132.32, 116.98, 126.24, 125.50, 106.52, 105.55
    ]
}
df1 = pd.DataFrame(data1)

data2 = {
    'ts': df1['ts'],  # data1의 ts 값을 그대로 사용
    'smp_da': [
 112.131, 92.21, 88.973, 90.822, 92.624, 88.468, 91.044, 107.99, 137.418, 130.909, 121.041,
        117.798, 109.092, 111.078, 126.305, 127.934, 126.719, 131.4, 131.058, 126.116, 123.307,
        114.455, 110.105, 111.338




    ]
}
df2 = pd.DataFrame(data2)

# ts를 KST로 변환
kst = timezone(timedelta(hours=9))
df1['ts'] = pd.to_datetime(df1['ts'], unit='s', utc=True).dt.tz_convert(kst)
df2['ts'] = pd.to_datetime(df2['ts'], unit='s', utc=True).dt.tz_convert(kst)

# e_F 값 계산
e_f_value = calculate_measure(df1['smp_da'], df2['smp_da'])
print(f'e_F: {e_f_value}')